# upperdeckripmaster3030 — bake the Section 9 arena materials in Blender → textures/*.png
#
#   npm run textures                      # all nine classes, 512px
#   npm run textures -- --size 1024       # …bigger
#   npm run textures -- --only deck,wall  # …one at a time, while authoring
#   npm run textures -- --no-ao           # skip the slow pass (AO is ~85% of the wall clock)
#
# WHY THIS EXISTS
# js/s9pc-world.js grew a value-noise fbm generator that paints albedo/normal/gloss onto a 2D
# canvas at load. It works, it ships, and it is the fallback — but a hand-written fbm in a JS
# loop is a very small tool next to a node graph, and the arenas read as flat boxes because the
# surfaces have no STRUCTURE in them: no joints with real depth, no crazing, no weave, no
# ripples. This authors each surface as a procedural node network and bakes it to a tiling map
# set, so the runtime cost becomes a fetch instead of nine 512² JS loops, and the authoring tool
# becomes Blender.
#
# ⚑ EVERY TEXEL HERE IS GENERATED BY THIS FILE. Nothing is downloaded, sampled, traced or
#   decimated from anyone else's work — same rule as scripts/blender/kit.py and models/README.md,
#   and the reason this can go into a minted token without a rights question.
#
# ── things that were MEASURED, not assumed ────────────────────────────────────────────────────
#
# ⚠ `scene.cycles.use_denoising` DEFAULTS ON, and with no denoise device (this container, any CI
#   box, any GPU-less machine) EVERY BAKE COMES BACK BLACK — while `bpy.ops.object.bake()` still
#   returns {'FINISHED'} and Blender logs only a mild "No device available to denoise on". Cost an
#   hour of staring at correct-looking node graphs producing 0,0,0. It is off, explicitly, below.
#
# ⚑ COLOUR MANAGEMENT, verified by baking a constant Emission of linear 0.5 and reading the PNG
#   bytes back: an image whose colorspace is 'sRGB' writes byte 188 (= the sRGB encode of 0.5),
#   one whose colorspace is 'Non-Color' writes byte 128 (raw). So albedo is baked into an sRGB
#   image (PlayCanvas loads it as PIXELFORMAT_SRGBA8 and decodes), and normal/ORM are baked into
#   Non-Color images (loaded as RGBA8, raw). `image.save()` — NOT `save_render()`, which would
#   push the scene view transform (Blender 4 defaults to AgX!) through a data map.
#
# ⚑ NORMAL-MAP CONVENTION AGREES WITH THE CANVAS GENERATOR — checked, not hoped. Baking a height
#   that rises with UV V gives G = 97/255, i.e. G < 0.5, which is OpenGL/+Y. Blender's V rises UP
#   the PNG, so that is "height falling down the PNG → G < 0.5"; the canvas path computes
#   ny = h[row+1] − h[row−1] with row running DOWN the PNG and emits the same sign. The two paths
#   are interchangeable, which is what makes the fallback a fallback rather than a different look.
#
# ⚑ TILING IS BY CONSTRUCTION, and then verified numerically anyway (see SEAM lines).
#   Blender's noise/voronoi nodes do not tile. The fix is to sample them on a TORUS: map u,v onto
#   two circles in 4D — (cos 2πu, sin 2πu, cos 2πv, sin 2πv) — using the 4D Vector+W inputs. A
#   circle of radius 1/2π has circumference exactly 1, so a "scale" of S along that circle is S
#   noise cells per tile, and going once round u returns to the identical sample. Anisotropy (the
#   brushed-metal grain, a wall's vertical weeping) is the two circles carrying DIFFERENT radii,
#   which stretches the pattern without ever breaking the loop. Seeding is a constant offset of
#   the whole torus — a translation of a closed loop is still a closed loop.
#   Structure (slab joints, brick courses, canvas weave) is built from FRACT/FLOOR of u,v with
#   INTEGER counts, which is exact rather than approximately periodic.
#
# ── what comes out ────────────────────────────────────────────────────────────────────────────
#   textures/<class>_albedo.png   sRGB, RGB.   NEUTRAL on purpose — see below.
#   textures/<class>_normal.png   Non-Color, RGB, tangent space.
#   textures/<class>_orm.png      Non-Color, RGB. R = ambient occlusion, G = roughness,
#                                 B = metalness. One fetch and one texture unit instead of two;
#                                 PlayCanvas reads them by channel (aoMapChannel/glossMapChannel).
#
# ⚑ THE ALBEDO MAPS ARE DELIBERATELY NEAR-NEUTRAL. js/s9pc-world.js multiplies them by a per-class
#   tint, and MATS_DAY — the daylight palette — was arrived at by measurement (CLAUDE.md records
#   the whole argument: near-white tints took DUST BOWL's saturation DOWN because ACES desaturates
#   as it compresses toward white). Baking colour into these maps would silently double-tint every
#   arena and throw that work away. So the maps carry LUMINANCE STRUCTURE and only a few percent of
#   hue variation; the palette stays where it was measured.

import bpy
import math
import os
import sys
import time

import numpy as np

TAU = math.pi * 2.0
R = 1.0 / TAU          # circle radius whose circumference is exactly 1 → "scale" == cells per tile


# ── tiny node-graph helpers ───────────────────────────────────────────────────────────────────
# Authoring a shader in Python is verbose enough that without these the material bodies below
# stop being readable, and an unreadable procedural texture is one nobody will ever tune.

def _is_sock(v):
    return isinstance(v, bpy.types.NodeSocket)


def _feed(nt, node, idx, v):
    if v is None:
        return
    if _is_sock(v):
        nt.links.new(v, node.inputs[idx])
    else:
        node.inputs[idx].default_value = v


def M(nt, op, a, b=None, c=None, clamp=False):
    """One Math node. Returns its output socket, so these nest."""
    n = nt.nodes.new('ShaderNodeMath')
    n.operation = op
    n.use_clamp = clamp
    for i, v in enumerate((a, b, c)):
        _feed(nt, n, i, v)
    return n.outputs[0]


def mix(nt, a, b, t):
    """a + (b−a)·t as ONE node — MULTIPLY_ADD is a*b+c."""
    return M(nt, 'MULTIPLY_ADD', M(nt, 'SUBTRACT', b, a), t, a)


def smooth(nt, x, e0, e1):
    """smoothstep, clamped. Used everywhere a mask needs an edge that is not a staircase."""
    t = M(nt, 'DIVIDE', M(nt, 'SUBTRACT', x, e0), (e1 - e0) if not _is_sock(e1) else e1, clamp=False)
    t = M(nt, 'CLAMP' if False else 'MINIMUM', M(nt, 'MAXIMUM', t, 0.0), 1.0)
    return M(nt, 'MULTIPLY', M(nt, 'MULTIPLY', t, t), M(nt, 'SUBTRACT', 3.0, M(nt, 'MULTIPLY', 2.0, t)))


def rgb(nt, r, g, b):
    n = nt.nodes.new('ShaderNodeCombineColor')
    _feed(nt, n, 0, r)
    _feed(nt, n, 1, g)
    _feed(nt, n, 2, b)
    return n.outputs[0]


def torus(nt, over=1.0):
    """UV → the four torus coordinates, built ONCE per material and shared by every sampler.

    ⚑ `over` is the OVERSCAN, and it has to be applied HERE rather than by scaling the mesh's UV
    attribute — that attribute is simultaneously where the shader reads and where the bake writes,
    so stretching it would move the pattern and the image together and change nothing. Scaling the
    coordinate inside the graph moves only the pattern: the plane still fills the padded image,
    but the tile the pattern draws now sits in the middle of it with a margin of real, evaluated
    texels all round, which is what the crop then keeps."""
    tc = nt.nodes.new('ShaderNodeTexCoord')
    sep = nt.nodes.new('ShaderNodeSeparateXYZ')
    nt.links.new(tc.outputs['UV'], sep.inputs[0])
    u, v = sep.outputs['X'], sep.outputs['Y']
    if over != 1.0:
        u = M(nt, 'MULTIPLY_ADD', M(nt, 'SUBTRACT', u, 0.5), over, 0.5)
        v = M(nt, 'MULTIPLY_ADD', M(nt, 'SUBTRACT', v, 0.5), over, 0.5)
    a = M(nt, 'MULTIPLY', u, TAU)
    b = M(nt, 'MULTIPLY', v, TAU)
    return {'u': u, 'v': v,
            'cu': M(nt, 'COSINE', a), 'su': M(nt, 'SINE', a),
            'cv': M(nt, 'COSINE', b), 'sv': M(nt, 'SINE', b)}


def _coord(nt, T, fu, fv, seed):
    """(vector, w) for a 4D sampler with `fu` cells around u and `fv` around v.

    fu ≠ fv is the anisotropy knob: it stretches the pattern along one axis without ever
    breaking periodicity, because each axis is still its own closed circle."""
    ru, rv = fu * R, fv * R
    ox, oy, oz, ow = (seed * 1.73) % 7.0, (seed * 3.11) % 5.0, (seed * 0.97) % 11.0, (seed * 2.31) % 3.0
    cx = nt.nodes.new('ShaderNodeCombineXYZ')
    _feed(nt, cx, 0, M(nt, 'MULTIPLY_ADD', T['cu'], ru, ox))
    _feed(nt, cx, 1, M(nt, 'MULTIPLY_ADD', T['su'], ru, oy))
    _feed(nt, cx, 2, M(nt, 'MULTIPLY_ADD', T['cv'], rv, oz))
    return cx.outputs[0], M(nt, 'MULTIPLY_ADD', T['sv'], rv, ow)


def noise(nt, T, fu, fv, seed=0, detail=4.0, rough=0.5, dist=0.0, lac=2.0):
    vec, w = _coord(nt, T, fu, fv, seed)
    n = nt.nodes.new('ShaderNodeTexNoise')
    n.noise_dimensions = '4D'
    nt.links.new(vec, n.inputs['Vector'])
    nt.links.new(w, n.inputs['W'])
    n.inputs['Scale'].default_value = 1.0        # the frequency lives in fu/fv, above
    n.inputs['Detail'].default_value = detail
    n.inputs['Roughness'].default_value = rough
    n.inputs['Distortion'].default_value = dist  # a periodic warp of a periodic field still tiles
    if 'Lacunarity' in n.inputs:
        n.inputs['Lacunarity'].default_value = lac
    return n.outputs['Fac']


def voro(nt, T, fu, fv, seed=0, feature='F1', out='Distance', randomness=1.0, smoothness=1.0):
    vec, w = _coord(nt, T, fu, fv, seed)
    n = nt.nodes.new('ShaderNodeTexVoronoi')
    n.voronoi_dimensions = '4D'
    n.feature = feature
    nt.links.new(vec, n.inputs['Vector'])
    nt.links.new(w, n.inputs['W'])
    n.inputs['Scale'].default_value = 1.0
    if 'Randomness' in n.inputs:
        n.inputs['Randomness'].default_value = randomness
    if 'Smoothness' in n.inputs:
        n.inputs['Smoothness'].default_value = smoothness
    return n.outputs[out]


def white(nt, a, b):
    """Per-CELL random. Fed FLOOR()s, so it is constant across a slab and different on the next."""
    n = nt.nodes.new('ShaderNodeTexWhiteNoise')
    n.noise_dimensions = '3D'
    c = nt.nodes.new('ShaderNodeCombineXYZ')
    _feed(nt, c, 0, a)
    _feed(nt, c, 1, b)
    _feed(nt, c, 2, 0.0)
    nt.links.new(c.outputs[0], n.inputs['Vector'])
    return n.outputs['Value']


def joints(nt, T, nx, ny, w, stagger=0.0):
    """Grid/brick joint mask: 1 inside a seam, 0 in the middle of a unit. Plus the cell indices.

    ⚑ nx/ny MUST be integers and, when staggered, ny must be EVEN — that is what makes the joint
    at u=0 the same joint as the one at u=1 and keeps the running bond consistent across the tile
    boundary. A non-integer count puts a half-brick at the seam, which is the classic way a
    "tileable" masonry texture turns out not to be."""
    ux = M(nt, 'MULTIPLY', T['u'], float(nx))
    vy = M(nt, 'MULTIPLY', T['v'], float(ny))
    row = M(nt, 'FLOOR', vy)
    uu = M(nt, 'FRACT', M(nt, 'MULTIPLY_ADD', row, stagger, ux))
    vv = M(nt, 'FRACT', vy)
    du = M(nt, 'MINIMUM', uu, M(nt, 'SUBTRACT', 1.0, uu))
    dv = M(nt, 'MINIMUM', vv, M(nt, 'SUBTRACT', 1.0, vv))
    d = M(nt, 'MINIMUM', M(nt, 'DIVIDE', du, w), M(nt, 'DIVIDE', dv, w))
    return {'j': M(nt, 'SUBTRACT', 1.0, M(nt, 'MINIMUM', d, 1.0)),
            'col': M(nt, 'FLOOR', M(nt, 'MULTIPLY_ADD', row, stagger, ux)), 'row': row}


def bands(nt, x, n, w):
    """A tileable stripe mask along one axis: 1 on the line, 0 between. n must be an integer."""
    f = M(nt, 'FRACT', M(nt, 'MULTIPLY', x, float(n)))
    d = M(nt, 'MINIMUM', f, M(nt, 'SUBTRACT', 1.0, f))
    return M(nt, 'SUBTRACT', 1.0, M(nt, 'MINIMUM', M(nt, 'DIVIDE', d, w), 1.0))


# ── the nine surfaces ─────────────────────────────────────────────────────────────────────────
# Each builder returns {col, rough, height} sockets. `col` is near-neutral (see the header);
# `rough` is real roughness, centred on 1 − MATS[key].gloss in js/s9pc-world.js so the class keeps
# the gloss it was tuned to; `height` is 0..~1 and gets scaled by the class's `relief` in metres.
#
# ⚠ The gloss/roughness pairing is a COUPLING between this file and js/s9pc-world.js's MATS table.
#   On the baked path the map wins (gloss = 1, glossInvert = true) — MATS.gloss then only drives
#   the canvas fallback. If you retune one, retune the other or the two paths stop matching.

def m_deck(nt, T):
    """Cast concrete slabs. Structure first: the eye locks onto joints, not onto noise."""
    J = joints(nt, T, 2, 2, 0.020)
    mott = noise(nt, T, 3, 3, seed=1, detail=6, rough=0.55)
    grit = noise(nt, T, 110, 110, seed=2, detail=2, rough=0.5)
    agg = voro(nt, T, 40, 40, seed=3, feature='F1')                 # exposed aggregate stones
    aggm = smooth(nt, agg, 0.30, 0.06)                              # near a cell centre → a stone
    cell = white(nt, J['col'], J['row'])                            # per-slab pour tone
    wear = noise(nt, T, 6, 6, seed=4, detail=3, rough=0.6)          # traffic polish, large blotches
    v = M(nt, 'ADD', 0.80, M(nt, 'ADD',
                             M(nt, 'MULTIPLY', M(nt, 'SUBTRACT', mott, 0.5), 0.11),
                             M(nt, 'ADD', M(nt, 'MULTIPLY', M(nt, 'SUBTRACT', grit, 0.5), 0.05),
                                          M(nt, 'MULTIPLY', M(nt, 'SUBTRACT', cell, 0.5), 0.07))))
    v = M(nt, 'MULTIPLY', v, M(nt, 'SUBTRACT', 1.0, M(nt, 'MULTIPLY', J['j'], 0.36)))
    v = M(nt, 'ADD', v, M(nt, 'MULTIPLY', aggm, 0.05))
    col = rgb(nt, v, M(nt, 'MULTIPLY', v, 0.995), M(nt, 'MULTIPLY', v, 1.015))
    rough = M(nt, 'SUBTRACT',
              M(nt, 'ADD', 0.66, M(nt, 'ADD', M(nt, 'MULTIPLY', M(nt, 'SUBTRACT', 1.0, mott), 0.09),
                                              M(nt, 'MULTIPLY', J['j'], 0.10))),
              M(nt, 'MULTIPLY', wear, 0.10))
    h = M(nt, 'SUBTRACT',
          M(nt, 'ADD', M(nt, 'MULTIPLY', mott, 0.25),
                       M(nt, 'ADD', M(nt, 'MULTIPLY', aggm, 0.55), M(nt, 'MULTIPLY', grit, 0.14))),
          M(nt, 'MULTIPLY', J['j'], 1.30))
    return {'col': col, 'rough': rough, 'height': h}


def m_wall(nt, T):
    """Rendered masonry: a running bond under thin plaster, weathered DOWNWARD.

    ⚑ The streaks run along v because a wall's uv is (world x or z, world y) — v IS vertical here.
    CLAUDE.md's arena-texturing note is the reason: it is the DIRECTION of the grime, not its
    amount, that stops the eye reading the repeat."""
    J = joints(nt, T, 4, 6, 0.030, stagger=0.5)
    plaster = noise(nt, T, 5, 5, seed=11, detail=6, rough=0.6)
    weep = noise(nt, T, 70, 3, seed=12, detail=4, rough=0.7)        # tall thin → runs down the wall
    craze = voro(nt, T, 14, 14, seed=13, feature='DISTANCE_TO_EDGE')
    crack = smooth(nt, craze, 0.05, 0.008)                          # hairline crazing at cell edges
    brick = white(nt, J['col'], J['row'])
    v = M(nt, 'ADD', 0.82, M(nt, 'ADD',
                             M(nt, 'MULTIPLY', M(nt, 'SUBTRACT', plaster, 0.5), 0.09),
                             M(nt, 'MULTIPLY', M(nt, 'SUBTRACT', brick, 0.5), 0.05)))
    v = M(nt, 'MULTIPLY', v, M(nt, 'SUBTRACT', 1.0, M(nt, 'MULTIPLY', J['j'], 0.30)))
    v = M(nt, 'MULTIPLY', v, M(nt, 'SUBTRACT', 1.0, M(nt, 'MULTIPLY', weep, 0.13)))
    v = M(nt, 'MULTIPLY', v, M(nt, 'SUBTRACT', 1.0, M(nt, 'MULTIPLY', crack, 0.22)))
    col = rgb(nt, M(nt, 'MULTIPLY', v, 1.005), v, M(nt, 'MULTIPLY', v, 0.985))
    rough = M(nt, 'ADD', 0.78, M(nt, 'ADD', M(nt, 'MULTIPLY', weep, 0.10),
                                            M(nt, 'MULTIPLY', J['j'], 0.06)))
    h = M(nt, 'SUBTRACT',
          M(nt, 'ADD', M(nt, 'MULTIPLY', plaster, 0.30), M(nt, 'MULTIPLY', M(nt, 'SUBTRACT', brick, 0.5), 0.30)),
          M(nt, 'ADD', M(nt, 'MULTIPLY', J['j'], 1.20), M(nt, 'MULTIPLY', crack, 0.45)))
    return {'col': col, 'rough': rough, 'height': h}


def m_metal(nt, T):
    """Brushed steel. Anisotropy IS the material — a metal with isotropic noise reads as plastic."""
    brush = noise(nt, T, 4, 300, seed=21, detail=2, rough=0.5)      # long grain along u
    fine = noise(nt, T, 8, 900, seed=22, detail=1, rough=0.5)
    scr = voro(nt, T, 6, 90, seed=23, feature='DISTANCE_TO_EDGE')   # stretched scratches
    scratch = smooth(nt, scr, 0.035, 0.004)
    panel = bands(nt, T['v'], 2, 0.010)                             # a seam every half tile
    v = M(nt, 'ADD', 0.86, M(nt, 'ADD', M(nt, 'MULTIPLY', M(nt, 'SUBTRACT', brush, 0.5), 0.10),
                                        M(nt, 'MULTIPLY', M(nt, 'SUBTRACT', fine, 0.5), 0.05)))
    v = M(nt, 'MULTIPLY', v, M(nt, 'SUBTRACT', 1.0, M(nt, 'MULTIPLY', panel, 0.28)))
    col = rgb(nt, M(nt, 'MULTIPLY', v, 0.99), v, M(nt, 'MULTIPLY', v, 1.03))
    rough = M(nt, 'SUBTRACT',
              M(nt, 'ADD', 0.30, M(nt, 'ADD', M(nt, 'MULTIPLY', M(nt, 'SUBTRACT', brush, 0.5), 0.22),
                                              M(nt, 'MULTIPLY', panel, 0.20))),
              M(nt, 'MULTIPLY', scratch, 0.12))
    h = M(nt, 'SUBTRACT', M(nt, 'ADD', M(nt, 'MULTIPLY', brush, 0.30), M(nt, 'MULTIPLY', fine, 0.16)),
          M(nt, 'ADD', M(nt, 'MULTIPLY', panel, 0.90), M(nt, 'MULTIPLY', scratch, 0.30)))
    return {'col': col, 'rough': rough, 'height': h}


def m_crate(nt, T):
    """Painted steel: paint film, chipped back to bare metal at the edges, with rolled ribs."""
    rib = bands(nt, T['u'], 4, 0.055)
    chip = noise(nt, T, 9, 9, seed=31, detail=5, rough=0.65, dist=0.6)
    worn = smooth(nt, chip, 0.60, 0.76)                             # threshold → the paint is gone
    grain = noise(nt, T, 60, 60, seed=32, detail=2, rough=0.5)
    scuff = noise(nt, T, 22, 4, seed=33, detail=3, rough=0.7)       # dragged along the floor
    v = M(nt, 'ADD', 0.86, M(nt, 'MULTIPLY', M(nt, 'SUBTRACT', grain, 0.5), 0.07))
    v = M(nt, 'MULTIPLY', v, M(nt, 'SUBTRACT', 1.0, M(nt, 'MULTIPLY', scuff, 0.08)))
    # bare metal is BRIGHTER and much less coloured than the paint over it; the map stays neutral
    # so the runtime tint keeps its job, so "bare" is expressed as value, not as hue
    v = mix(nt, v, M(nt, 'MULTIPLY', v, 0.72), worn)
    v = M(nt, 'MULTIPLY', v, M(nt, 'SUBTRACT', 1.0, M(nt, 'MULTIPLY', rib, 0.16)))
    col = rgb(nt, v, M(nt, 'MULTIPLY', v, 0.99), M(nt, 'MULTIPLY', v, 0.985))
    rough = M(nt, 'ADD', 0.48, M(nt, 'ADD', M(nt, 'MULTIPLY', worn, 0.26),
                                            M(nt, 'MULTIPLY', M(nt, 'SUBTRACT', grain, 0.5), 0.10)))
    h = M(nt, 'ADD', M(nt, 'MULTIPLY', rib, 0.85),
          M(nt, 'SUBTRACT', M(nt, 'MULTIPLY', grain, 0.16), M(nt, 'MULTIPLY', worn, 0.55)))
    return {'col': col, 'rough': rough, 'height': h}


def m_cab(nt, T):
    """Arcade-cabinet lacquer. Almost flat on purpose: what sells it is orange peel and seams.

    ⚑ This is the class CLAUDE.md's "studio look" note is really about — a cabinet is two thirds
    of ARCADE PIT's geometry and it must stay QUIET, or the post stack's unsharp pass sharpens a
    field of speckle across most of the frame."""
    peel = noise(nt, T, 34, 34, seed=41, detail=2, rough=0.4)
    seamu = bands(nt, T['u'], 2, 0.006)
    seamv = bands(nt, T['v'], 3, 0.006)
    seam = M(nt, 'MAXIMUM', seamu, seamv)
    dust = noise(nt, T, 5, 5, seed=42, detail=4, rough=0.5)
    v = M(nt, 'ADD', 0.90, M(nt, 'MULTIPLY', M(nt, 'SUBTRACT', peel, 0.5), 0.030))
    v = M(nt, 'MULTIPLY', v, M(nt, 'SUBTRACT', 1.0, M(nt, 'MULTIPLY', seam, 0.34)))
    v = M(nt, 'MULTIPLY', v, M(nt, 'SUBTRACT', 1.0, M(nt, 'MULTIPLY', dust, 0.045)))
    col = rgb(nt, v, v, M(nt, 'MULTIPLY', v, 1.02))
    rough = M(nt, 'ADD', 0.22, M(nt, 'ADD', M(nt, 'MULTIPLY', M(nt, 'SUBTRACT', peel, 0.5), 0.09),
                                            M(nt, 'MULTIPLY', M(nt, 'ADD', seam, dust), 0.14)))
    h = M(nt, 'SUBTRACT', M(nt, 'MULTIPLY', peel, 0.30), M(nt, 'MULTIPLY', seam, 1.10))
    return {'col': col, 'rough': rough, 'height': h}


def m_water(nt, T):
    """Pool water. The albedo is nearly a flat field — ALL of the read is in the normal.

    Two crossed ripple trains at different scales plus a slow swell, because one noise moving one
    way reads as a texture and two crossing read as a surface."""
    a = noise(nt, T, 26, 20, seed=51, detail=3, rough=0.45, dist=0.9)
    b = noise(nt, T, 13, 34, seed=52, detail=3, rough=0.45, dist=0.7)
    swell = noise(nt, T, 3, 3, seed=53, detail=2, rough=0.5)
    caus = voro(nt, T, 10, 10, seed=54, feature='DISTANCE_TO_EDGE')
    caustic = smooth(nt, caus, 0.16, 0.02)
    v = M(nt, 'ADD', 0.88, M(nt, 'ADD', M(nt, 'MULTIPLY', M(nt, 'SUBTRACT', swell, 0.5), 0.05),
                                        M(nt, 'MULTIPLY', caustic, 0.10)))
    col = rgb(nt, M(nt, 'MULTIPLY', v, 0.97), v, M(nt, 'MULTIPLY', v, 1.02))
    rough = M(nt, 'ADD', 0.06, M(nt, 'MULTIPLY', M(nt, 'SUBTRACT', M(nt, 'ADD', a, b), 1.0), 0.05))
    h = M(nt, 'ADD', M(nt, 'MULTIPLY', a, 0.5), M(nt, 'ADD', M(nt, 'MULTIPLY', b, 0.4),
                                                             M(nt, 'MULTIPLY', swell, 0.3)))
    return {'col': col, 'rough': rough, 'height': h}


def m_plant(nt, T):
    """Massed foliage seen as a surface: clumps, not leaves. Height carries almost all of it."""
    clump = voro(nt, T, 9, 9, seed=61, feature='SMOOTH_F1', smoothness=0.6)
    leaf = voro(nt, T, 30, 30, seed=62, feature='F1', randomness=1.0)
    shade = noise(nt, T, 4, 4, seed=63, detail=5, rough=0.65)
    fine = noise(nt, T, 90, 90, seed=64, detail=2, rough=0.5)
    lm = smooth(nt, leaf, 0.34, 0.05)
    v = M(nt, 'ADD', 0.78, M(nt, 'ADD', M(nt, 'MULTIPLY', M(nt, 'SUBTRACT', shade, 0.5), 0.20),
                                        M(nt, 'MULTIPLY', lm, 0.16)))
    v = M(nt, 'MULTIPLY', v, M(nt, 'SUBTRACT', 1.0, M(nt, 'MULTIPLY', clump, 0.30)))
    v = M(nt, 'MULTIPLY', v, M(nt, 'SUBTRACT', 1.0, M(nt, 'MULTIPLY', M(nt, 'SUBTRACT', fine, 0.5), 0.14)))
    col = rgb(nt, M(nt, 'MULTIPLY', v, 0.97), v, M(nt, 'MULTIPLY', v, 0.94))
    rough = M(nt, 'ADD', 0.74, M(nt, 'MULTIPLY', M(nt, 'SUBTRACT', shade, 0.5), 0.14))
    h = M(nt, 'ADD', M(nt, 'MULTIPLY', lm, 0.75),
          M(nt, 'SUBTRACT', M(nt, 'MULTIPLY', shade, 0.35), M(nt, 'MULTIPLY', clump, 0.55)))
    return {'col': col, 'rough': rough, 'height': h}


def m_awning(nt, T):
    """Canvas: warp and weft, then panel seams. A weave is two stripe fields, not a noise."""
    warp = bands(nt, T['u'], 96, 0.34)
    weft = bands(nt, T['v'], 96, 0.34)
    weave = M(nt, 'SUBTRACT', warp, M(nt, 'MULTIPLY', M(nt, 'MULTIPLY', warp, weft), 0.5))
    fuzz = noise(nt, T, 130, 130, seed=71, detail=2, rough=0.5)
    panel = bands(nt, T['u'], 4, 0.012)                             # stitched panel joins
    sag = noise(nt, T, 3, 6, seed=72, detail=3, rough=0.55)
    v = M(nt, 'ADD', 0.86, M(nt, 'ADD', M(nt, 'MULTIPLY', M(nt, 'SUBTRACT', weave, 0.5), 0.10),
                                        M(nt, 'MULTIPLY', M(nt, 'SUBTRACT', fuzz, 0.5), 0.05)))
    v = M(nt, 'MULTIPLY', v, M(nt, 'SUBTRACT', 1.0, M(nt, 'MULTIPLY', panel, 0.22)))
    v = M(nt, 'MULTIPLY', v, M(nt, 'SUBTRACT', 1.0, M(nt, 'MULTIPLY', sag, 0.09)))
    col = rgb(nt, v, M(nt, 'MULTIPLY', v, 0.995), M(nt, 'MULTIPLY', v, 0.98))
    rough = M(nt, 'ADD', 0.56, M(nt, 'ADD', M(nt, 'MULTIPLY', fuzz, 0.14),
                                            M(nt, 'MULTIPLY', M(nt, 'SUBTRACT', weave, 0.5), 0.08)))
    h = M(nt, 'SUBTRACT', M(nt, 'ADD', M(nt, 'MULTIPLY', weave, 0.55), M(nt, 'MULTIPLY', sag, 0.35)),
          M(nt, 'MULTIPLY', panel, 0.80))
    return {'col': col, 'rough': rough, 'height': h}


def m_trim(nt, T):
    """Cut stone: the brightest thing in frame and only on edges, so it must stay clean and read
    as CUT — a chamfer line and a little veining, nothing granular."""
    J = joints(nt, T, 1, 2, 0.028)
    vein = noise(nt, T, 6, 3, seed=81, detail=6, rough=0.7, dist=1.4)
    grain = noise(nt, T, 140, 140, seed=82, detail=2, rough=0.5)
    pit = voro(nt, T, 26, 26, seed=83, feature='F1')
    pits = smooth(nt, pit, 0.12, 0.02)
    v = M(nt, 'ADD', 0.90, M(nt, 'ADD', M(nt, 'MULTIPLY', M(nt, 'SUBTRACT', vein, 0.5), 0.06),
                                        M(nt, 'MULTIPLY', M(nt, 'SUBTRACT', grain, 0.5), 0.035)))
    v = M(nt, 'MULTIPLY', v, M(nt, 'SUBTRACT', 1.0, M(nt, 'MULTIPLY', J['j'], 0.26)))
    v = M(nt, 'MULTIPLY', v, M(nt, 'SUBTRACT', 1.0, M(nt, 'MULTIPLY', pits, 0.10)))
    col = rgb(nt, v, M(nt, 'MULTIPLY', v, 0.998), M(nt, 'MULTIPLY', v, 0.99))
    rough = M(nt, 'ADD', 0.68, M(nt, 'ADD', M(nt, 'MULTIPLY', pits, 0.14),
                                            M(nt, 'MULTIPLY', J['j'], 0.06)))
    h = M(nt, 'SUBTRACT', M(nt, 'ADD', M(nt, 'MULTIPLY', vein, 0.16), M(nt, 'MULTIPLY', grain, 0.12)),
          M(nt, 'ADD', M(nt, 'MULTIPLY', J['j'], 1.25), M(nt, 'MULTIPLY', pits, 0.55)))
    return {'col': col, 'rough': rough, 'height': h}


# key, builder, relief in metres over one tile, metalness (→ ORM blue), AO on?, AO ray distance
CLASSES = [
    ('deck',   m_deck,   0.014, 0.04, True,  0.055),
    ('wall',   m_wall,   0.016, 0.03, True,  0.060),
    ('metal',  m_metal,  0.004, 0.94, False, 0.020),
    ('crate',  m_crate,  0.010, 0.30, True,  0.045),
    ('cab',    m_cab,    0.004, 0.14, False, 0.020),
    ('water',  m_water,  0.007, 0.02, False, 0.020),
    ('plant',  m_plant,  0.022, 0.00, True,  0.070),
    ('awning', m_awning, 0.006, 0.02, True,  0.030),
    ('trim',   m_trim,   0.012, 0.02, True,  0.050),
]


# ── bake harness ──────────────────────────────────────────────────────────────────────────────

def arg(name, default=None):
    a = sys.argv[sys.argv.index('--') + 1:] if '--' in sys.argv else []
    for i, s in enumerate(a):
        if s == name:
            return a[i + 1] if i + 1 < len(a) else True
        if s.startswith(name + '='):
            return s.split('=', 1)[1]
    return default


def clear_nodes(nt):
    for n in list(nt.nodes):
        nt.nodes.remove(n)


def img_array(img):
    """Pixels as (h, w, 4). ⚑ images.new() makes a BYTE buffer, so these are already the stored
    bytes/255 — 0.5 linear in an sRGB image reads back as 188/255, in a Non-Color one as 128/255.
    That means crop-and-rewrite below is lossless and needs no colour conversion of its own."""
    a = np.empty(len(img.pixels), dtype=np.float32)
    img.pixels.foreach_get(a)
    return a.reshape(img.size[1], img.size[0], 4)


def crop(img, name, N, pad, colorspace):
    """Take the interior N×N out of a padded bake. See PAD in main()."""
    a = img_array(img)[pad:pad + N, pad:pad + N, :]
    o = bpy.data.images.new(name, N, N, alpha=False)
    o.colorspace_settings.name = colorspace
    o.pixels.foreach_set(np.ascontiguousarray(a).reshape(-1))
    o.update()
    return o


def seam_ratio(a):
    """How much bigger is the step ACROSS the wrap than the steps immediately either side of it?

    1.0 means the wrap is indistinguishable from its own neighbours — i.e. it tiles.

    ⚠ The obvious test — "is the wrap step bigger than the AVERAGE step in the tile" — is not a
    fair one and it sent me chasing a bug that was not there. `deck`'s tile boundary is a slab
    JOINT by construction, the steepest gradient in the whole map, while the average step is
    dominated by flat slab interior; that alone scored 1.31 on a texture that tiles perfectly.
    Comparing the wrap against the two steps ADJACENT to it compares like with like.

    ⚠ And "are opposite edges equal" is not the test either — in a real texture they SHOULD
    differ, being one pixel apart rather than the same pixel. Testing for equality is how a
    texture ends up mirrored and called seamless."""
    g = a[:, :, :3].mean(axis=2)
    seam_u = np.abs(g[:, 0] - g[:, -1]).mean()
    seam_v = np.abs(g[0, :] - g[-1, :]).mean()
    near_u = (np.abs(g[:, 1] - g[:, 0]).mean() + np.abs(g[:, -1] - g[:, -2]).mean()) * 0.5
    near_v = (np.abs(g[1, :] - g[0, :]).mean() + np.abs(g[-1, :] - g[-2, :]).mean()) * 0.5
    return (seam_u / near_u if near_u > 1e-9 else 0.0,
            seam_v / near_v if near_v > 1e-9 else 0.0)


def save(img, path):
    img.filepath_raw = path
    img.file_format = 'PNG'
    img.save()


def main():
    t_all = time.time()
    N = int(arg('--size', 512))
    out = arg('--out') or os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'textures')
    out = os.path.abspath(out)
    only = arg('--only')
    only = set(only.split(',')) if only else None
    do_ao = not arg('--no-ao')
    os.makedirs(out, exist_ok=True)

    bpy.ops.wm.read_factory_settings(use_empty=True)
    sc = bpy.context.scene
    sc.render.engine = 'CYCLES'
    sc.cycles.device = 'CPU'
    sc.cycles.use_denoising = False      # ⚠ see the header — ON gives silently BLACK bakes here
    # ⚠ AND SET THE SAMPLE COUNT BEFORE THE FIRST BAKE, NOT INSIDE THE AO BRANCH. Cycles' default
    #   is 4096, so an EMIT bake — which is exact at ONE sample, there is nothing stochastic in an
    #   emission shader — quietly ran 4096 of them and a single 256px class took over two minutes
    #   instead of under one second. The AO pass sets its own count and puts this back.
    sc.cycles.samples = 1
    sc.cycles.use_adaptive_sampling = False
    sc.view_settings.view_transform = 'Standard'
    sc.render.bake.use_pass_direct = False
    sc.render.bake.use_pass_indirect = False
    sc.render.bake.margin = 8
    sc.world = bpy.data.worlds.new('w')

    # ⚑ PAD, AND WHY IT IS NOT OPTIONAL — the shading-only maps are baked at N+2·PAD with the
    #   plane's UVs scaled by the same ratio about the centre, then the interior N×N is cropped
    #   out. Measured before/after on `deck`, seam ratio (step across the wrap ÷ a typical step
    #   inside the tile, so 1.0 = indistinguishable):
    #       albedo 1.31 → ~1.0     normal 13.21 → ~1.0     orm 1.69 → ~1.0
    #   The albedo/ORM seam was the bake MARGIN: a UV island that fills the image edge-to-edge has
    #   nowhere to grow into, so Blender fills the outermost texels by extension instead of by
    #   evaluating the shader. The 13× on the NORMAL map is worse and has a different cause — the
    #   Bump node is a DERIVATIVE, so it needs a valid neighbourhood, and at the mesh boundary
    #   there is none. Both vanish once every output texel sits well inside the plane. The pattern
    #   itself is periodic in u,v with period 1, so evaluating it outside [0,1] is exactly the wrap.
    PAD = 4
    N2 = N + 2 * PAD
    OVER = float(N2) / float(N)

    # flat: everything shading-only (albedo / roughness / height / normal). One quad is enough —
    # a bake is per-texel, and a dense mesh only slows it down.
    bpy.ops.mesh.primitive_plane_add(size=1.0)
    flat = bpy.context.object
    flat.name = 'flat'

    # relief: the SAME tile as real geometry, displaced by the baked height, ringed by eight
    # copies of itself so the ambient occlusion at the tile border sees its own neighbours.
    # Without the ring the AO map darkens toward every edge and the arena grows a visible grid.
    bpy.ops.mesh.primitive_grid_add(size=1.0, x_subdivisions=257, y_subdivisions=257)
    relief = bpy.context.object
    relief.name = 'relief'
    rmat = bpy.data.materials.new('relief')
    rmat.use_nodes = True
    relief.data.materials.append(rmat)
    clear_nodes(rmat.node_tree)
    rtex = rmat.node_tree.nodes.new('ShaderNodeTexImage')
    rmat.node_tree.nodes.active = rtex
    ring = []
    for dx in (-1, 0, 1):
        for dy in (-1, 0, 1):
            if dx == 0 and dy == 0:
                continue
            c = relief.copy()
            c.data = relief.data                       # linked — the ring costs no extra mesh
            bpy.context.collection.objects.link(c)
            c.location = (dx, dy, 0)
            ring.append(c)

    def bake_into(ob, img, kind):
        bpy.ops.object.select_all(action='DESELECT')
        ob.select_set(True)
        bpy.context.view_layer.objects.active = ob
        t = time.time()
        bpy.ops.object.bake(type=kind)
        return (time.time() - t) * 1000.0

    written = []
    for key, build, relief_m, metalness, ao_on, ao_dist in CLASSES:
        if only and key not in only:
            continue
        t_cls = time.time()

        mat = bpy.data.materials.new('m_' + key)
        mat.use_nodes = True
        flat.data.materials.clear()
        flat.data.materials.append(mat)
        nt = mat.node_tree
        clear_nodes(nt)
        outn = nt.nodes.new('ShaderNodeOutputMaterial')
        em = nt.nodes.new('ShaderNodeEmission')
        nt.links.new(em.outputs[0], outn.inputs['Surface'])
        tex = nt.nodes.new('ShaderNodeTexImage')
        nt.nodes.active = tex

        S = build(nt, torus(nt, OVER))

        # 1. albedo — sRGB image, so image.save() applies the sRGB encode (verified: 0.5 → 188)
        albp = bpy.data.images.new(key + '_ap', N2, N2, alpha=False)
        tex.image = albp
        nt.links.new(S['col'], em.inputs['Color'])
        ms_a = bake_into(flat, albp, 'EMIT')
        alb = crop(albp, key + '_a', N, PAD, 'sRGB')

        # 2. roughness and 3. height — Non-Color, raw values straight through
        rghp = bpy.data.images.new(key + '_rp', N2, N2, alpha=False)
        rghp.colorspace_settings.name = 'Non-Color'
        tex.image = rghp
        nt.links.new(S['rough'], em.inputs['Color'])
        ms_r = bake_into(flat, rghp, 'EMIT')
        rgh = crop(rghp, key + '_r', N, PAD, 'Non-Color')

        hgtp = bpy.data.images.new(key + '_hp', N2, N2, alpha=False)
        hgtp.colorspace_settings.name = 'Non-Color'
        tex.image = hgtp
        nt.links.new(S['height'], em.inputs['Color'])
        ms_h = bake_into(flat, hgtp, 'EMIT')
        hgt = crop(hgtp, key + '_h', N, PAD, 'Non-Color')

        # 4. normal — a Principled with nothing but a Bump on it, so the NORMAL bake records
        # exactly the relief and nothing else. `Distance` is the metres of relief over one tile;
        # `Strength` stays 1 because a strength blend would be a second, hidden, scale factor.
        nt.links.remove(em.outputs[0].links[0])
        bsdf = nt.nodes.new('ShaderNodeBsdfPrincipled')
        bump = nt.nodes.new('ShaderNodeBump')
        bump.inputs['Strength'].default_value = 1.0
        bump.inputs['Distance'].default_value = relief_m
        nt.links.new(S['height'], bump.inputs['Height'])
        nt.links.new(bump.outputs['Normal'], bsdf.inputs['Normal'])
        nt.links.new(bsdf.outputs[0], outn.inputs['Surface'])
        nrmp = bpy.data.images.new(key + '_np', N2, N2, alpha=False)
        nrmp.colorspace_settings.name = 'Non-Color'
        tex.image = nrmp
        ms_n = bake_into(flat, nrmp, 'NORMAL')
        nrm = crop(nrmp, key + '_n', N, PAD, 'Non-Color')

        # 5. ambient occlusion — a REAL trace against displaced geometry, not a re-tinted mask.
        ao = None
        ms_o = 0.0
        if ao_on and do_ao:
            btex = bpy.data.textures.get('ht_' + key) or bpy.data.textures.new('ht_' + key, type='IMAGE')
            btex.image = hgt
            for m in list(relief.modifiers):
                relief.modifiers.remove(m)
            md = relief.modifiers.new('disp', 'DISPLACE')
            md.texture = btex
            md.texture_coords = 'UV'
            md.mid_level = 0.5
            md.strength = relief_m * 2.0        # height is 0..1 about 0.5, so ±relief_m of throw
            for c in ring:                      # object copies do NOT share a modifier stack
                for m in list(c.modifiers):
                    c.modifiers.remove(m)
                cm = c.modifiers.new('disp', 'DISPLACE')
                cm.texture = btex
                cm.texture_coords = 'UV'
                cm.mid_level = 0.5
                cm.strength = md.strength
            ao = bpy.data.images.new(key + '_o', N, N, alpha=False)
            ao.colorspace_settings.name = 'Non-Color'
            rtex.image = ao
            sc.world.light_settings.distance = ao_dist
            sc.cycles.samples = 24
            ms_o = bake_into(relief, ao, 'AO')
            sc.cycles.samples = 1

        # 6. pack O/R/M into one RGB image. Two greyscale PNGs would be two fetches and two
        # texture units for three numbers; PlayCanvas can address them by channel.
        A = img_array(rgh)
        orm = np.empty_like(A)
        orm[:, :, 0] = img_array(ao)[:, :, 0] if ao is not None else 1.0
        orm[:, :, 1] = A[:, :, 0]
        orm[:, :, 2] = metalness
        orm[:, :, 3] = 1.0
        oi = bpy.data.images.new(key + '_orm', N, N, alpha=False)
        oi.colorspace_settings.name = 'Non-Color'
        oi.pixels.foreach_set(orm.reshape(-1))
        oi.update()

        for suffix, img in (('albedo', alb), ('normal', nrm), ('orm', oi)):
            p = os.path.join(out, '%s_%s.png' % (key, suffix))
            save(img, p)
            su, sv = seam_ratio(img_array(img))
            print('SEAM %s %s u=%.3f v=%.3f' % (key, suffix, su, sv))
            print('BAKED %s %s %s %d' % (key, suffix, p, os.path.getsize(p)))

        print('CLASS %s %.0fms (albedo %.0f rough %.0f height %.0f normal %.0f ao %.0f)'
              % (key, (time.time() - t_cls) * 1000.0, ms_a, ms_r, ms_h, ms_n, ms_o))
        written.append(key)

    print('TOTAL %d classes %.1fs size=%d' % (len(written), time.time() - t_all, N))


if __name__ == '__main__':
    sc = None
    try:
        main()
    except Exception as e:                       # a traceback in Blender's log is easy to miss
        import traceback
        traceback.print_exc()
        print('BAKE_FAIL %s' % e)
        sys.exit(1)
