# upperdeckripmaster3030 — CC0-lineage props and environment patterns, authored in Blender.
#
#   blender --background --factory-startup -P scripts/blender/build-cc0-props.py -- models/cc0/cc0-props.glb
#   (or just: npm run cc0)
#
# WHAT THIS IS. A first set of original game geometry whose *design vocabulary* is studied from
# CC0 crypto-art. Every triangle here is generated by this script — nothing is traced, imported,
# sampled or decimated from anyone else's file. The licence dossier that governs which sources
# were allowed to inform it is docs/CC0-SOURCES.md; the per-asset lineage is models/cc0/README.md.
#
# ⚠ THE LINE THIS FILE HOLDS. A palette, a proportion and a construction rule are not
# copyrightable. A character is. So what crosses over is: "flat fill, hard edge, strict grid"
# (Nouns), "black is the ground and white never appears" (XCOPY, measured), "four colours per
# piece" (Blitmap), "a list withheld for others to interpret" (Loot), "ordered dither instead of
# grey" (Anonymice). What does not cross over is any recognisable shape. In particular there is
# **no Noun-shaped eyewear anywhere in this file** — the noggles are the Nouns mark, and a mark is
# trademark territory that CC0 does not touch.
#
# ── conventions ──────────────────────────────────────────────────────────────────────────────
# kit.py's LEVEL frame: Blender Z-up, so `z` is height. export_glb() turns that into glTF Y-up,
# which is what js/ronin-glb.js reads. Props are authored BASE AT z=0 and roughly 1 unit tall,
# the same contract build-craft.py's prop_* use: the loader normalises height to exactly 1, so
# what survives is the proportion, not the size.
#
# EVERY PROP IS ONE OBJECT. The renderers draw a prop as a single VBO with a single tint, so a
# prop split into parts would only cost draw calls and could not be coloured separately anyway.
# Colour lives in models/cc0/skins.json, not in the mesh.

import sys
import os
import math

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bpy                                                                       # noqa: E402
import kit                                                                       # noqa: E402

TAU = math.pi * 2

# The grid. Nouns art is a 32×32 lattice of flat fills and its whole legibility comes from
# nothing ever landing between cells. U = 1/32 of the prop's authored height is the same
# discipline in three dimensions: quantise every coordinate through q() and the silhouette stays
# readable when the prop is 12 pixels tall on a phone.
U = 1.0 / 32.0


def q(v, u=U):
    """Snap to the lattice. The point is not tidiness — it is that a quantised silhouette
    survives being drawn small, which is the only size most of these are ever seen at."""
    return round(v / u) * u


def qbox(part, c, s, rz=0.0):
    """kit.Part.box with both centre and size snapped. Sizes snap to a HALF cell so a box can be
    one-and-a-half cells thick; centres snap to the full cell so faces still line up."""
    return part.box((q(c[0]), q(c[1]), q(c[2])),
                    (q(s[0], U / 2), q(s[1], U / 2), q(s[2], U / 2)), rz)


# ── ordered dither, as a shared source of truth ──────────────────────────────────────────────
# The same 8×8 Bayer matrix drives prop_dither's relief here and the dither FX tile in
# scripts/build-cc0.mjs. Anonymice's discipline is that there is no grey — a value is either on
# or off, and the *pattern* carries the tone. Expressed as geometry that means a stud is either
# present or absent; there is no half-height stud.

def bayer8():
    """Recursive 8×8 ordered-dither threshold matrix, values 0..63."""
    m = [[0]]
    while len(m) < 8:
        n = len(m)
        m = [[4 * v for v in row] + [4 * v + 2 for v in row] for row in m] + \
            [[4 * v + 3 for v in row] + [4 * v + 1 for v in row] for row in m]
        # the standard recursion is (4v, 4v+2 / 4v+3, 4v+1); n is only here to keep the loop honest
        assert len(m) == n * 2
    return m


BAYER = bayer8()


# ── props ────────────────────────────────────────────────────────────────────────────────────

def prop_totem():
    """Lineage: Nouns — flat fill, hard edge, strict grid, legibility from silhouette alone.

    A stacked idol whose every step is a whole number of cells. There is no taper and no curve:
    each stage either is or is not wider than the one below it, which is the 2-D pixel rule
    ("a pixel is on or off") pushed into a third axis. The two side ears exist so the silhouette
    is asymmetric about the vertical — a perfectly symmetrical stack reads as a bollard.
    """
    p = kit.Part('prop_totem')
    # plinth → body → collar → head, each a discrete jump
    qbox(p, (0, 0, 0.030), (0.44, 0.44, 0.060))
    qbox(p, (0, 0, 0.090), (0.36, 0.36, 0.060))
    qbox(p, (0, 0, 0.310), (0.28, 0.28, 0.380))          # body
    qbox(p, (0, 0, 0.530), (0.34, 0.34, 0.060))          # collar — the one overhang
    qbox(p, (0, 0, 0.700), (0.26, 0.26, 0.280))          # neck/upper body
    qbox(p, (0, 0, 0.880), (0.38, 0.30, 0.100))          # head, wider than tall
    qbox(p, (0, 0, 0.960), (0.22, 0.22, 0.060))          # crown
    # ears — offset in x only, and by different amounts, so the shape has a front
    qbox(p, (-0.24, 0, 0.870), (0.12, 0.18, 0.080))
    qbox(p, (0.28, 0, 0.860), (0.16, 0.18, 0.060))
    # a recessed band read as a "slot": two lips with a thinner middle already there
    for sx in (-1, 1):
        qbox(p, (sx * 0.15, 0, 0.310), (0.02, 0.30, 0.240))
    return p


# ⚠ THE GRID IS A FAMILY RULE, NOT A HOUSE RULE — and the first render proved it the hard way.
# prop_slice and prop_scanbar were originally built through qbox() like everything else, and the
# 1/32 lattice ate them: scanbar's 18-step density ramp snapped onto ~8 evenly spaced rungs and
# rendered as a LADDER, which is the exact failure the docstring below warns against. Quantisation
# is the Nouns discipline and it is right for the flat-fill family, where legibility comes from
# nothing landing between cells. The XCOPY family is the opposite — a continuous ramp and a
# sub-cell displacement ARE the subject — so these two build from raw boxes.
#
# The one thing that stays quantised here is prop_slice's LATERAL tear, because a quantised
# sideways jump is what datamosh actually looks like: a block copied from the wrong offset.

def prop_slice():
    """Lineage: XCOPY — datamosh / slice-offset, done in geometry rather than in a shader.

    A monolith cut into horizontal bands, each shifted sideways and in depth by a seeded amount.
    The reason it works as an OBJECT and not just as a post-effect: a shader glitch is flat and
    disappears the moment the camera moves, whereas a displaced slab still occludes correctly and
    still catches the key light on its exposed edge. The glitch becomes something you can walk
    round.

    Fixed seed, so this prop is byte-identical on every build.
    """
    p = kit.Part('prop_slice')
    r = kit.rng(3030)
    n = 26
    h = 1.0 / n
    for i in range(n):
        z = (i + 0.5) * h
        # most bands sit still; a minority tear. A uniform stagger reads as a staircase, not a
        # glitch — the signature of datamosh is that the corruption is INTERMITTENT.
        torn = r.random() < 0.42
        dx = q(r.uniform(-0.15, 0.15)) if torn else 0.0     # quantised: a block from the wrong offset
        dy = q(r.uniform(-0.07, 0.07), U / 2) if torn else 0.0
        w = 0.40 + (r.uniform(-0.07, 0.12) if torn else 0.0)
        p.box((dx, dy, z), (w, 0.34, h * 0.92))
    p.box((0, 0, 0.5), (0.16, 0.16, 1.0))   # the intact core the bands slid off
    return p


def prop_scanbar():
    """Lineage: XCOPY — the scanline, as architecture.

    Two uprights carrying horizontal bars whose SPACING ramps GEOMETRICALLY: dense enough at the
    base to read as a solid, wide open at the top. The ratio between the first gap and the last is
    about 12:1, and it needs to be that extreme — at 3:1 the eye reads "ladder with uneven rungs",
    which is a mistake, rather than "density gradient", which is a scanline.

    The bar thickness tracks the gap, so the DUTY CYCLE stays roughly constant while the frequency
    falls. That is what a CRT actually does, and it is why the bottom reads as surface and the top
    reads as air.
    """
    p = kit.Part('prop_scanbar')
    for sx in (-1, 1):
        p.box((sx * 0.20, 0, 0.50), (0.055, 0.10, 1.00))
    z, i = 0.035, 0
    while z < 0.975:
        step = 0.012 * (1.16 ** i)
        p.box((0, 0, z), (0.40, 0.075, min(0.026, step * 0.62)))
        z += step
        i += 1
    p.box((0, 0, 0.015), (0.52, 0.16, 0.030))              # foot
    return p


def prop_lump():
    """Lineage: goblintown — grotesque, wet, lumpen, aggressively asymmetric.

    Deliberately NOT a creature. It is a growth/boulder prop: what is borrowed is the *attitude*
    (nothing is symmetrical, nothing is smooth, the mass sags to one side), not a face. A goblin
    with a face would be a derivative character; a lopsided lump is a shape language.

    Built by piling overlapping ellipsoids. Overlap rather than boolean union is correct here —
    the interior faces are never seen, the renderer is depth-tested, and a boolean would cost a
    modifier evaluation and produce worse topology for no visible gain.
    """
    p = kit.Part('prop_lump')
    r = kit.rng(1111)
    blobs = [
        (0.00, 0.00, 0.26, 0.30, 0.26, 0.26),
        (0.14, 0.05, 0.42, 0.24, 0.21, 0.22),
        (-0.10, -0.04, 0.52, 0.19, 0.17, 0.20),
        (0.20, -0.08, 0.20, 0.17, 0.15, 0.16),
        (-0.18, 0.07, 0.18, 0.15, 0.14, 0.14),
        (0.06, 0.02, 0.68, 0.13, 0.12, 0.15),
        (0.24, 0.10, 0.58, 0.09, 0.09, 0.11),          # the one nub that breaks the mass
    ]
    for (cx, cy, cz, rx, ry, rz) in blobs:
        ellipsoid(p, (cx, cy, cz), (rx, ry, rz), seg=10, rings=6, jitter=r)
    return p


def prop_slate():
    """Lineage: Loot — a list as an artwork, and art deliberately withheld for others to fill in.

    Loot's whole move is that it ships no image: white monospace on black, and the picture is
    your problem. As an object that becomes a standing slab with an EMPTY recessed panel. The
    recess is the asset. Whatever the game wants to put in it — a leaderboard, a card's stat
    block, the FX text tile from models/cc0/tex — goes in later, which is exactly the bargain
    Loot proposed.

    No Loot item names are used. Item names are the one part of Loot that is actually authored,
    and none of them are here.
    """
    p = kit.Part('prop_slate')
    qbox(p, (0, 0, 0.030), (0.62, 0.26, 0.060))            # foot
    qbox(p, (0, 0.05, 0.520), (0.54, 0.05, 0.860))         # back plate — the recess floor
    # frame: four rails standing proud of the back plate, so the panel is a real recess and reads
    # as one at grazing angles instead of only head-on
    qbox(p, (0, -0.01, 0.930), (0.58, 0.09, 0.070))        # head rail
    qbox(p, (0, -0.01, 0.115), (0.58, 0.09, 0.070))        # sill
    for sx in (-1, 1):
        qbox(p, (sx * 0.26, -0.01, 0.520), (0.06, 0.09, 0.900))
    qbox(p, (0, -0.01, 0.560), (0.44, 0.03, 0.020))        # one rule across the panel: a list has lines
    qbox(p, (0, -0.01, 0.400), (0.44, 0.03, 0.020))
    return p


def prop_dither():
    """Lineage: Anonymice / Blitmap — ordered dither instead of grey, and a hard colour count.

    A block whose front face carries an 8×8 Bayer field in relief: a stud is present when the
    threshold passes, absent when it doesn't. There is no half stud, because the entire idea is
    that tone comes from PATTERN and not from value. Read from the same BAYER matrix that
    generates the dither FX tile, so the prop and the texture are literally the same pattern.

    Tri cost is the reason only one face gets studs: 64 studs × 12 tris is already 768.
    """
    p = kit.Part('prop_dither')
    qbox(p, (0, 0.06, 0.46), (0.66, 0.16, 0.86))           # the slab
    qbox(p, (0, 0.02, 0.025), (0.74, 0.24, 0.050))         # foot
    s = 0.072                                              # stud pitch
    x0, z0 = -3.5 * s, 0.46 - 3.5 * s
    for gy in range(8):
        for gx in range(8):
            # threshold ramps with height, so the face fades from solid at the bottom to sparse
            # at the top — a dither GRADIENT, which is the thing worth showing
            level = int(63 * (gy / 7.0))
            if BAYER[gy][gx] >= level:
                p.box((x0 + gx * s, -0.03, z0 + gy * s), (s * 0.72, 0.05, s * 0.72))
    return p


# ── environment patterns ─────────────────────────────────────────────────────────────────────
# These are modular: authored so copies butt against each other on the grid. They are the
# repeatable furniture a level is made of, not set pieces.

def env_deck():
    """A 1×1 modular floor tile with a dithered edge.

    The interesting part is the EDGE. A tile with a hard border reads as a tile and the repeat
    becomes obvious immediately; a tile whose border dissolves into an ordered-dither fringe
    reads as one continuous surface even when you can see six of them. Same trick a 1-bit artist
    uses to fake a soft edge with no greys available.
    """
    p = kit.Part('env_deck')
    p.box((0, 0, -0.03), (1.0, 1.0, 0.06))                 # deck
    s = 1.0 / 16.0
    for i in range(16):
        for j in range(16):
            # distance from the tile edge, in cells; dither the outer three rings
            d = min(i, j, 15 - i, 15 - j)
            if d > 2:
                continue
            if BAYER[i % 8][j % 8] >= int(63 * (d / 3.0)):
                continue
            p.box((-0.5 + (i + 0.5) * s, -0.5 + (j + 0.5) * s, 0.012), (s * 0.9, s * 0.9, 0.024))
    return p


def env_bars():
    """A wall segment of vertical bars at quantised depths — a level meter as architecture.

    Depths come off a fixed seed, so the same wall is the same wall every build. Bars, not a flat
    wall, because Section 9's whole cover model wants silhouettes you can peek between, and
    because a flat wall is the one surface a procedural material can never rescue.
    """
    p = kit.Part('env_bars')
    r = kit.rng(2626)
    n = 14
    w = 1.0 / n
    for i in range(n):
        d = q(0.06 + r.random() * 0.20)                    # how far this bar stands proud
        h = q(0.55 + r.random() * 0.45)
        p.box((-0.5 + (i + 0.5) * w, d * 0.5, h * 0.5), (w * 0.8, d, h))
    p.box((0, 0.02, 0.02), (1.0, 0.22, 0.04))              # kick rail ties them together
    return p


def env_gate():
    """An octagonal gate ring — a portal/threshold piece.

    Octagonal on purpose. kit.ring() makes a proper torus and dogfight already has one; the point
    of THIS one is that a quantised polygon belongs to the same family as the rest of the set. A
    24-sided ring next to a 32-grid totem looks like it came from a different game.
    """
    p = kit.Part('env_gate')
    seg = 8
    R = 0.42
    for i in range(seg):
        a0 = TAU * (i + 0.5) / seg
        # each straight segment of the octagon, as one box rotated to the chord
        chord = 2.0 * R * math.sin(math.pi / seg)
        cx, cy = math.cos(a0) * R * math.cos(math.pi / seg), math.sin(a0) * R * math.cos(math.pi / seg)
        p.box((cx, 0.0, 0.52 + cy), (chord * 1.06, 0.10, 0.09), 0.0)
        # rotate the box about the ring's own axis by rebuilding it: kit's rz spins about Z, and
        # this ring stands in the XZ plane, so the segments are placed and then tilted by hand
        b = len(p.v) - 8
        ca, sa = math.cos(a0 + math.pi / 2), math.sin(a0 + math.pi / 2)
        for k in range(b, len(p.v)):
            x, y, z = p.v[k]
            lx, lz = x - cx, z - (0.52 + cy)
            p.v[k] = (cx + lx * ca - lz * sa, y, (0.52 + cy) + lx * sa + lz * ca)
    for k in range(4):                                      # inner tabs at the diagonals
        a = math.pi / 4 + k * math.pi / 2
        p.box((math.cos(a) * 0.31, 0.0, 0.52 + math.sin(a) * 0.31), (0.07, 0.12, 0.07))
    p.box((0, 0, 0.05), (0.30, 0.22, 0.10))                 # foot
    return p


# ── a local primitive kit.py does not have ───────────────────────────────────────────────────
# kit.py is shared and off-limits for this job, and an ellipsoid is only needed by prop_lump, so
# it lives here rather than in the shared kit. If a second caller ever wants it, that is the
# moment to promote it — one caller is not a primitive, it is a helper.

def ellipsoid(part, c, r, seg=12, rings=6, jitter=None):
    """UV ellipsoid appended into an existing Part. `jitter` (a random.Random) roughens the
    radius per vertex, which is what stops a pile of these reading as a pile of eggs."""
    base = len(part.v)
    part.v.append((c[0], c[1], c[2] + r[2]))                       # north pole
    for i in range(1, rings):
        phi = math.pi * i / rings
        sp, cp = math.sin(phi), math.cos(phi)
        for j in range(seg):
            th = TAU * j / seg
            k = 1.0 + (jitter.uniform(-0.11, 0.11) if jitter else 0.0)
            part.v.append((c[0] + math.cos(th) * sp * r[0] * k,
                           c[1] + math.sin(th) * sp * r[1] * k,
                           c[2] + cp * r[2] * k))
    part.v.append((c[0], c[1], c[2] - r[2]))                       # south pole
    south = len(part.v) - 1
    for j in range(seg):                                           # north cap
        part.f.append((base, base + 1 + (j + 1) % seg, base + 1 + j))
    for i in range(rings - 2):                                     # bands
        a = base + 1 + i * seg
        b = a + seg
        for j in range(seg):
            j2 = (j + 1) % seg
            part.f.append((a + j, a + j2, b + j2, b + j))
    last = base + 1 + (rings - 2) * seg
    for j in range(seg):                                           # south cap
        part.f.append((south, last + j, last + (j + 1) % seg))
    return part


def main():
    argv = sys.argv[sys.argv.index('--') + 1:] if '--' in sys.argv else []
    out = argv[0] if argv else 'models/cc0/cc0-props.glb'

    kit.reset()
    for build in (prop_totem, prop_slice, prop_scanbar, prop_lump, prop_slate, prop_dither,
                  env_deck, env_bars, env_gate):
        build().emit()
    kit.export_glb(out)


main()
