# upperdeckripmaster3030 — level kit: primitives for building game levels in Blender.
#
# Levels here are AUTHORED IN CODE, not sculpted. That is a deliberate choice and it buys three
# things this project specifically needs:
#
#   1. LICENCE. Every triangle is generated by a script in this repo, so it is unambiguously our
#      own work. Nothing here can turn into a rights problem inside a minted token — which is
#      the standing rule in models/README.md and the reason broly.obj and VADER never landed.
#   2. REPRODUCIBILITY. Same seed, same level, byte for byte. A level is its script plus a seed,
#      so a variant costs a number rather than a re-export, and review is a diff.
#   3. WEIGHT. We choose the tri budget instead of discovering it. A sculpted architectural
#      export ran 93 MB / 661k tris; these run a few hundred KB.
#
# ── conventions ────────────────────────────────────────────────────────────────────────────
# Authored in Blender's native Z-UP; the OBJ exporter converts to the Y-up the game wants, so
# `z` is height everywhere in this file and in the level scripts.
#
# EVERY COLLIDABLE VOLUME IS ITS OWN OBJECT. scripts/bake-world.mjs emits exactly one AABB per
# OBJ object, so a floor and a railing merged into one object would collide as the single box
# that encloses both — you would walk into thin air at the railing's height. Group by what the
# player should bump into, not by what shares a material.
#
# ⚠ Bake authored levels with `--minTris 0`. bake-world drops objects under 40 triangles as
#   clutter, which is right for a scanned city and wrong here: a crate is 12 triangles, and the
#   default would silently delete most of the level.

import bpy
import math
import random

TAU = math.pi * 2


def reset():
    """Empty scene. Levels build from nothing so a stale object can't leak into an export."""
    bpy.ops.wm.read_factory_settings(use_empty=True)


class Part:
    """Accumulates primitives into ONE named mesh — and therefore one collision box.

    Use a Part per thing the player treats as a solid: a cabinet, a pillar, one step of a
    staircase. Do NOT accumulate a whole room into one Part; see the AABB note above.
    """

    def __init__(self, name):
        self.name = name
        self.v = []
        self.f = []

    def box(self, c, s, rz=0.0):
        """Axis-aligned box (optionally spun about Z) at centre `c` with full size `s`."""
        hx, hy, hz = s[0] / 2.0, s[1] / 2.0, s[2] / 2.0
        ca, sa = math.cos(rz), math.sin(rz)
        local = [(-hx, -hy, -hz), (hx, -hy, -hz), (hx, hy, -hz), (-hx, hy, -hz),
                 (-hx, -hy, hz), (hx, -hy, hz), (hx, hy, hz), (-hx, hy, hz)]
        b = len(self.v)
        for (x, y, z) in local:
            self.v.append((c[0] + x * ca - y * sa, c[1] + x * sa + y * ca, c[2] + z))
        self.f += [(b + 0, b + 3, b + 2, b + 1), (b + 4, b + 5, b + 6, b + 7),
                   (b + 0, b + 1, b + 5, b + 4), (b + 1, b + 2, b + 6, b + 5),
                   (b + 2, b + 3, b + 7, b + 6), (b + 3, b + 0, b + 4, b + 7)]
        return self

    def cyl(self, c, r, h, seg=12, r2=None):
        """Solid capped cylinder (or truncated cone when r2 is given), standing on Z.

        ⚠ Always capped. Reaching for this to make a ring — a cornice, a balcony, a walkway
        annulus — roofs the space over as a solid drum instead. Ring box segments round the
        radius for those; see the wall/balcony loops in build-level.py.
        """
        if r2 is None:
            r2 = r
        b = len(self.v)
        for i in range(seg):
            a = TAU * i / seg
            self.v.append((c[0] + math.cos(a) * r, c[1] + math.sin(a) * r, c[2] - h / 2.0))
        for i in range(seg):
            a = TAU * i / seg
            self.v.append((c[0] + math.cos(a) * r2, c[1] + math.sin(a) * r2, c[2] + h / 2.0))
        for i in range(seg):
            j = (i + 1) % seg
            self.f.append((b + i, b + j, b + seg + j, b + seg + i))
        self.f.append(tuple(b + i for i in range(seg - 1, -1, -1)))          # bottom cap
        self.f.append(tuple(b + seg + i for i in range(seg)))                # top cap
        return self

    def wedge(self, c, s, rz=0.0, flip=False):
        """Triangular prism — ramps, roof pitches, the angled control deck of a cabinet."""
        hx, hy, hz = s[0] / 2.0, s[1] / 2.0, s[2] / 2.0
        ca, sa = math.cos(rz), math.sin(rz)
        lo, hi = (hx, -hx) if flip else (-hx, hx)
        local = [(lo, -hy, -hz), (hi, -hy, -hz), (hi, -hy, hz),
                 (lo, hy, -hz), (hi, hy, -hz), (hi, hy, hz)]
        b = len(self.v)
        for (x, y, z) in local:
            self.v.append((c[0] + x * ca - y * sa, c[1] + x * sa + y * ca, c[2] + z))
        self.f += [(b + 0, b + 2, b + 1), (b + 3, b + 4, b + 5),
                   (b + 0, b + 1, b + 4, b + 3), (b + 1, b + 2, b + 5, b + 4),
                   (b + 2, b + 0, b + 3, b + 5)]
        return self

    def emit(self):
        """Realise as a Blender object. Empty Parts are skipped rather than exported hollow."""
        if not self.f:
            return None
        me = bpy.data.meshes.new(self.name)
        me.from_pydata(self.v, [], self.f)
        me.validate()
        me.update()
        ob = bpy.data.objects.new(self.name, me)
        bpy.context.scene.collection.objects.link(ob)
        return ob


def solid(name, c, s, rz=0.0):
    """One box, one object, one collision AABB. The workhorse."""
    return Part(name).box(c, s, rz).emit()


def post(name, c, r, h, seg=10):
    return Part(name).cyl(c, r, h, seg).emit()


def stairs(name, base, rise, run, width, steps, axis='x', sign=1):
    """A flight as SEPARATE step objects, so the player walks up it instead of into a ramp-
    shaped box. Verticality is the whole point of these levels — RoninWorld's leap and boost
    only read as movement if there is something to land on."""
    out = []
    for i in range(steps):
        h = rise * (i + 1)
        if axis == 'x':
            c = (base[0] + sign * (i + 0.5) * run, base[1], base[2] + h / 2.0)
            s = (run, width, h)
        else:
            c = (base[0], base[1] + sign * (i + 0.5) * run, base[2] + h / 2.0)
            s = (width, run, h)
        out.append(solid('%s_step%02d' % (name, i), c, s))
    return out


def railing(name, a, b, height=1.1, post_every=2.2, r=0.07):
    """Posts plus a top rail. Reads as a ledge you can see over — and as a real edge in fog."""
    dx, dy = b[0] - a[0], b[1] - a[1]
    length = math.hypot(dx, dy) or 1.0
    n = max(2, int(length / post_every) + 1)
    out = []
    for i in range(n):
        t = i / (n - 1.0)
        out.append(post('%s_post%02d' % (name, i),
                        (a[0] + dx * t, a[1] + dy * t, a[2] + height / 2.0), r, height, 6))
    mid = (a[0] + dx / 2.0, a[1] + dy / 2.0, a[2] + height)
    out.append(solid('%s_rail' % name, mid, (length, r * 2.6, r * 2.2), math.atan2(dy, dx)))
    return out


def arcade_cabinet(name, c, rz=0.0, w=1.0, d=1.05, h=1.95):
    """The throughline object: the machine that promises you win something tangible.

    Built as one Part on purpose — a cabinet is a single solid to bump into, and its silhouette
    (tall body, angled control deck, overhanging marquee) is what has to read at play distance.
    """
    p = Part(name)
    p.box((c[0], c[1], c[2] + h / 2.0), (w, d, h), rz)                                   # body
    p.box((c[0], c[1] - d * 0.42, c[2] + h * 0.52), (w * 0.94, d * 0.34, h * 0.30), rz)  # screen bezel
    p.wedge((c[0], c[1] - d * 0.62, c[2] + h * 0.30), (d * 0.5, w * 0.92, 0.30), rz + math.pi / 2)
    p.box((c[0], c[1] - d * 0.10, c[2] + h + 0.13), (w * 1.06, d * 0.9, 0.26), rz)       # marquee
    return p.emit()


def claw_machine(name, c, rz=0.0, w=1.35, d=1.35, h=2.2):
    """Prize crane: a glass box you can see the prize through and probably will not get it.
    The anti-casino in one object — the promise is the product."""
    p = Part(name)
    p.box((c[0], c[1], c[2] + 0.45), (w, d, 0.9), rz)                                    # base
    for sx in (-1, 1):
        for sy in (-1, 1):
            p.box((c[0] + sx * w * 0.46, c[1] + sy * d * 0.46, c[2] + 1.5), (0.09, 0.09, 1.2), rz)
    p.box((c[0], c[1], c[2] + h + 0.12), (w * 1.04, d * 1.04, 0.24), rz)                 # cap
    p.box((c[0], c[1], c[2] + 1.92), (w * 0.5, 0.12, 0.12), rz)                          # crane rail
    return p.emit()


def plinth(name, c, rz=0.0, w=0.85, h=1.15):
    """Auction plinth under glass — the promise of value received, on a pedestal."""
    p = Part(name)
    p.box((c[0], c[1], c[2] + 0.06), (w * 1.25, w * 1.25, 0.12), rz)                     # foot
    p.box((c[0], c[1], c[2] + h / 2.0), (w, w, h), rz)                                   # column
    p.box((c[0], c[1], c[2] + h + 0.05), (w * 1.2, w * 1.2, 0.1), rz)                    # cap
    p.box((c[0], c[1], c[2] + h + 0.55), (w * 0.66, w * 0.5, 0.9), rz)                   # vitrine
    return p.emit()


def crate(name, c, s=0.9, rz=0.0):
    p = Part(name)
    p.box((c[0], c[1], c[2] + s / 2.0), (s, s, s), rz)
    for sx in (-1, 1):                                                                   # corner banding
        p.box((c[0] + sx * s * 0.46, c[1], c[2] + s / 2.0), (s * 0.09, s * 1.02, s * 1.02), rz)
    return p.emit()


def ring(name, c, r_major, r_minor, seg=24, ring_seg=8, rx=0.0):
    """A torus — the race gate you fly through.

    Built by hand rather than with bpy.ops.mesh.primitive_torus_add because the operator drops a
    mesh at the 3D cursor with its own transform and rotation mode, and this kit's whole contract
    is that a Part's vertices are already where they belong. `rx` tips it upright so the hole
    faces down the flight path instead of at the sky.
    """
    p = Part(name)
    ca, sa = math.cos(rx), math.sin(rx)
    base = len(p.v)
    for i in range(seg):
        a = TAU * i / seg
        cx, cy = math.cos(a) * r_major, math.sin(a) * r_major
        for j in range(ring_seg):
            b = TAU * j / ring_seg
            rr, zz = math.cos(b) * r_minor, math.sin(b) * r_minor
            x = cx + math.cos(a) * rr
            y = cy + math.sin(a) * rr
            z = zz
            # tip about X so the gate stands upright
            p.v.append((c[0] + x, c[1] + y * ca - z * sa, c[2] + y * sa + z * ca))
    for i in range(seg):
        i2 = (i + 1) % seg
        for j in range(ring_seg):
            j2 = (j + 1) % ring_seg
            p.f.append((base + i * ring_seg + j,  base + i2 * ring_seg + j,
                        base + i2 * ring_seg + j2, base + i * ring_seg + j2))
    return p


# ── aircraft frame ──────────────────────────────────────────────────────────────────────────
# foil() and hull() share one convention, and it is NOT the level convention above:
#
#     +x = nose (chord runs fore/aft) · ±y = span · +z = up
#
# Levels are built around a floor and a player, so up is the axis that matters; an aircraft is
# built around a centreline, so the long axis is. Author a craft nose-along-+x and rotate the
# finished object at export time to whatever the renderer wants — see scripts/blender/
# build-craft.py, which turns it -90° about z so glTF's +z comes out the nose.


def foil(part, root, tip, chord_r, chord_t, thick_r, thick_t, sweep=0.0, axis='y'):
    """A tapered lifting surface — wing, tailplane, fin.

    Lofts a 4-sided section from root to tip, narrowing in both chord (front-to-back) and
    thickness. `sweep` slides the tip aft (negative = swept back, the usual case). Crude next
    to a real aerofoil, and exactly right at the size a fighter reads on screen: what carries
    is the PLANFORM, and a swept taper reads as a wing from any angle a dogfight puts you at.

    `axis='y'` is a horizontal surface (wing, tailplane) — span runs across, thickness up.
    `axis='z'` is a vertical one (fin, rudder) — span runs up, thickness across. Without the
    second case a fin has to be faked with a squashed wing, which shades wrong because the
    thin dimension ends up on the wrong axis and the whole surface lights like a floor.

    Appends into an existing Part so a whole aircraft stays ONE object — dogfight draws a ship
    as a single VBO, so splitting it into parts would only cost draw calls.
    """
    def sect(centre, chord, thick):
        cx, cy, cz = centre
        h, t = chord / 2.0, thick / 2.0
        if axis == 'z':
            return [(cx - h, cy - t, cz), (cx + h, cy - t, cz), (cx + h, cy + t, cz), (cx - h, cy + t, cz)]
        return [(cx - h, cy, cz - t), (cx + h, cy, cz - t), (cx + h, cy, cz + t), (cx - h, cy, cz + t)]
    a = sect(root, chord_r, thick_r)
    b = sect((tip[0] + sweep, tip[1], tip[2]), chord_t, thick_t)
    base = len(part.v)
    part.v.extend(a); part.v.extend(b)
    for k in range(4):
        k2 = (k + 1) % 4
        part.f.append((base + k, base + k2, base + 4 + k2, base + 4 + k))
    part.f.append((base + 3, base + 2, base + 1, base + 0))       # root cap
    part.f.append((base + 4, base + 5, base + 6, base + 7))       # tip cap
    return part


def hull(part, sections):
    """Loft a CHAIN of rectangular stations into a fuselage, nose-last along +x.

    `sections` = [(x, width, height, dz), ...] ordered tail→nose. `width` runs across the span,
    `height` up, and `dz` lifts that station so a spine can rise and a chin can drop.

    This is the one shape foil() cannot make: foil lofts a single segment, and a fuselage built
    as a run of separate foils meets at duplicated vertices, so every station shades as a hard
    crease ring. Chaining through shared vertices is the whole point.

    Four-sided on purpose. The procedural craft this replaces is flat-panelled, and dogfight's
    look is neon low-poly — a smooth 16-sided body would read as a different game.
    """
    idx = []
    for (x, w, h, dz) in sections:
        hw, hh = w / 2.0, h / 2.0
        base = len(part.v)
        part.v.extend([(x, -hw, dz - hh), (x, hw, dz - hh), (x, hw, dz + hh), (x, -hw, dz + hh)])
        idx.append(base)
    for i in range(len(idx) - 1):
        a, b = idx[i], idx[i + 1]
        for k in range(4):
            k2 = (k + 1) % 4
            part.f.append((a + k, a + k2, b + k2, b + k))
    part.f.append((idx[0] + 3, idx[0] + 2, idx[0] + 1, idx[0] + 0))            # tail cap
    part.f.append((idx[-1] + 0, idx[-1] + 1, idx[-1] + 2, idx[-1] + 3))        # nose cap
    return part


def spawn(name, c):
    """An authored spawn point, emitted as a tiny marker object named `spawn_*`.

    scripts/bake-world.mjs lifts these out of the geometry — they never become triangles or a
    collision box — and records the transformed position. Going through the OBJ rather than a
    sidecar means the marker rides the exact same recentre/rescale the level does, so a spawn
    cannot drift away from the floor it was authored on.

    Author these on open floor deliberately. RoninWorld.findSpawn() will spiral out to rescue a
    buried one, but that is a safety net, not a design — Section 9 shipped DUST BOWL with 7 of
    10 spawns relocated and it read as a broken map.
    """
    return Part('spawn_' + name).box((c[0], c[1], c[2] + 0.1), (0.2, 0.2, 0.2)).emit()


def rng(seed):
    """Seeded, so a level is reproducible from its script and a number alone."""
    return random.Random(seed)


def export_obj(path, triangulate=True):
    """Write the scene as OBJ in the Y-up orientation bake-world.mjs expects.

    Materials and UVs are dropped: the renderer shades level geometry with its own procedural
    material system (js/ronin3d.js `uMat`), so exporting them would only inflate the file.
    """
    import os
    d = os.path.dirname(os.path.abspath(path))
    if not os.path.isdir(d):
        raise SystemExit('EXPORT_FAIL output directory is not a directory: %s' % d)
    kw = dict(filepath=path, forward_axis='NEGATIVE_Z', up_axis='Y',
              export_materials=False, export_uv=False, export_normals=True,
              export_triangulated_mesh=triangulate)
    try:
        bpy.ops.wm.obj_export(**kw)
    except (AttributeError, TypeError):                                                   # pre-4.0 exporter
        bpy.ops.export_scene.obj(filepath=path, axis_forward='-Z', axis_up='Y',
                                 use_materials=False, use_uvs=False, use_triangles=triangulate)
    # Blender's exporter reports nothing on a bad path, so confirm the bytes exist rather than
    # trusting the operator — an "EXPORTED" line over a file that was never written is worse
    # than a crash, because the next stage bakes stale geometry and nobody looks again.
    if not os.path.isfile(path) or os.path.getsize(path) < 64:
        raise SystemExit('EXPORT_FAIL nothing written to %s' % path)
    n = sum(len(o.data.polygons) for o in bpy.data.objects if o.type == 'MESH')
    print('EXPORTED %s — %d objects, ~%d faces, %d KB'
          % (path, len([o for o in bpy.data.objects if o.type == 'MESH']), n,
             os.path.getsize(path) // 1024))


def export_glb(path):
    """Write the scene as one GLB — for MODELS, where export_obj() is for levels.

    A level goes out as OBJ because bake-world.mjs re-reads it, decimates it and emits .wld.
    A model is loaded as-is by js/ronin-glb.js, so it may as well be shipped in the format that
    loader already speaks: one binary file, every object a named part, no sidecars.

    glTF's Y-up conversion is the exporter's default and is exactly what RoninGLB expects — the
    loader does no axis fixing of its own, it just walks the node transforms. Materials, UVs,
    skins and animation are all dropped: the renderer colours geometry per draw call, so a
    baked material would be dead weight that also has to be licence-cleared.
    """
    import os
    d = os.path.dirname(os.path.abspath(path))
    if not os.path.isdir(d):
        raise SystemExit('EXPORT_FAIL output directory is not a directory: %s' % d)
    if not path.endswith('.glb'):
        raise SystemExit('EXPORT_FAIL GLB path must end in .glb: %s' % path)
    kw = dict(filepath=path, export_format='GLB', export_yup=True, export_apply=True,
              export_materials='NONE', export_normals=True, export_texcoords=False,
              export_animations=False, export_skins=False,
              export_draco_mesh_compression_enable=False)
    try:
        bpy.ops.export_scene.gltf(**kw)
    except TypeError:                                                       # older arg spelling
        bpy.ops.export_scene.gltf(filepath=path, export_format='GLB', export_yup=True,
                                  export_apply=True, export_materials='NONE')
    # Same reason as export_obj: the operator is silent on a bad path, and an "EXPORTED" line
    # over a file that was never written means the game quietly ships yesterday's geometry.
    if not os.path.isfile(path) or os.path.getsize(path) < 64:
        raise SystemExit('EXPORT_FAIL nothing written to %s' % path)
    meshes = [o for o in bpy.data.objects if o.type == 'MESH']
    print('EXPORTED %s — %d parts, ~%d faces, %d KB'
          % (path, len(meshes), sum(len(o.data.polygons) for o in meshes),
             os.path.getsize(path) // 1024))
    for o in sorted(meshes, key=lambda m: m.name):
        b = [o.matrix_world @ v.co for v in o.data.vertices]
        lo = [min(p[i] for p in b) for i in range(3)]
        hi = [max(p[i] for p in b) for i in range(3)]
        print('  PART %-14s %5d tris  extent %.2f × %.2f × %.2f'
              % (o.name, len(o.data.loop_triangles) or len(o.data.polygons) * 2,
                 hi[0] - lo[0], hi[1] - lo[1], hi[2] - lo[2]))
