/* ripmaster3030studios — HOW A LAYERED CARD IS DESCRIBED.  `CardLayers`
 *
 *   CardLayers.load(artUrl, o) -> Promise<spec|null>   find + parse the sidecar, never rejects
 *   CardLayers.normalize(raw, base) -> spec|null       validate + fill defaults, never throws
 *   CardLayers.SCHEMA / .KINDS / .VERSION
 *
 * ══ WHY THERE IS A SCHEMA AT ALL ═══════════════════════════════════════════════════════════
 *
 * A card is a LENS, and a lens has depth. A flat PNG on a tilting plane is a picture of a card;
 * separated plates that slide against each other are an object. But the depth cannot be
 * INFERRED — and this is the whole reason this file exists rather than an auto-segmenter:
 *
 * ⛔ **We do not fake layers by segmenting flat art.** Every card in the repo today is a flat
 *    placeholder plate (cards/manifest.json, 196 of them) or a flat hero scan
 *    (cards/hero-manifest.json). Splitting one on luminance or on a background-colour key
 *    produces halos, cut-off hair and a subject that shears off its own shadow — and it would
 *    let us claim the feature works on a deck where it does not. Layers come from the ARTIST,
 *    authored as separate images, or the card is a single flat plate and says so.
 *
 * ⚑ **Therefore the default answer is null.** `load()` resolving to null is the NORMAL case, not
 *    an error case, and `Card3D` must render exactly the card it renders today when it gets one.
 *    That is what makes this safe to ship against 196 unlayered cards.
 *
 * ══ THE SIDECAR ════════════════════════════════════════════════════════════════════════════
 *
 * Beside the art. `art/hero/34.webp` -> `art/hero/34.layers.json`. A sidecar rather than a field
 * in the manifest because the manifests are generated by ingest scripts this file does not own,
 * and because the description belongs with the pictures it describes — move the folder, the
 * layers come too.
 *
 *   {
 *     "v": 1,
 *     "size": [1024, 1536],                  // authored pixel size (informative)
 *     "layers": [
 *       { "id":"bg",      "src":"34.bg.webp",      "z":0.00, "fit":"full" },
 *       { "id":"mid",     "src":"34.mid.webp",     "z":0.35 },
 *       { "id":"subject", "src":"34.subject.webp", "z":0.62, "relief":1.0,
 *                         "normal":"34.subject.n.webp" },
 *       { "id":"fx",      "src":"34.fx.webp",      "z":0.85, "blend":"add",
 *                         "drive":{ "gain":"burn", "min":0.15, "max":1.0 } },
 *       { "id":"foil",    "src":"34.foil.webp",    "z":1.00, "blend":"add", "foil":true }
 *     ]
 *   }
 *
 * FIELDS, and what each is FOR
 *   id       label. Free text; `KINDS` are the conventional five but nothing enforces them.
 *   src      image URL, resolved against the sidecar. RGBA — alpha is the cut-out.
 *   z        0..1 through the card's thickness. 0 = against the backing, 1 = at the glass.
 *            ⚑ This is the PHYSICAL stack: it decides occlusion, sort order and which plate the
 *            key light rakes first. It is deliberately NOT the parallax amount.
 *   par      parallax gain, default `2z - 1` (front layers slide against back ones, the same
 *            convention the flat card already uses). ⚑ Separate from `z` because at 28° fov and
 *            a 3.4-unit camera, 3 hundredths of a card's thickness moves a plate by 0.8% of its
 *            width — true to the geometry and invisible. The apparent depth of a card in the
 *            hand is a drawing decision, so it is an authored number.
 *   fit      "art" (default, 0.90 of the face — inside the bevel) or "full" (0.99, edge to
 *            edge). A layer that parallaxes must not reveal its own edge: backgrounds go full.
 *   scale    extra multiplier on the plate size, default 1.
 *   relief   0..1, how much the layer is embossed. Default 0 for every layer except the
 *            bottom-most, which gets 0.6. ⚠ Relief is a 512² CPU blur + Sobel PER LAYER; five
 *            layers of it on a phone is five times the cost for an effect only the top layer
 *            usually needs. Opt in.
 *   normal   an AUTHORED tangent-space normal map, used instead of deriving one from luminance.
 *            Always better when it exists — the derived one is a guess about what is raised.
 *   blend    "normal" (default) or "add".
 *   foil     true marks the layer as the holographic sweep — it travels rather than sitting
 *            still, and it is the layer `prefers-reduced-motion` freezes.
 *   drive    { gain: "burn"|"price"|"depth", min, max } — ties this layer's emissive gain to a
 *            live market dial from `js/lens-state.js`. Absent = constant.
 *
 * FAILS OPEN AT EVERY STEP. No fetch, a 404, malformed JSON, a layer with no `src`, a `z`
 * outside 0..1 — the bad layer is dropped, and if nothing survives the whole spec is null and
 * the card is the flat card. Nothing here ever throws.
 */
(function (global) {
  'use strict';

  var VERSION = 1;
  var KINDS = ['bg', 'mid', 'subject', 'fx', 'foil'];
  var MAX_LAYERS = 8;          // a card is a card. Eight plates is already more than reads.

  function clamp(v, lo, hi) { return v < lo ? lo : v > hi ? hi : v; }
  function num(v, dflt) { var n = typeof v === 'number' ? v : parseFloat(v); return isFinite(n) ? n : dflt; }

  function abs(u, base) {
    if (!u || typeof u !== 'string') return null;
    try { return new URL(u, base).href; } catch (e) { return null; }
  }

  /** Turn whatever we were handed into a spec we can trust, or null. Never throws. */
  function normalize(raw, base) {
    try {
      if (!raw || typeof raw !== 'object') return null;
      var arr = Array.isArray(raw) ? raw : raw.layers;
      if (!Array.isArray(arr) || !arr.length) return null;
      if (raw.v !== undefined && num(raw.v, VERSION) > VERSION) return null;   // newer than we speak

      var out = [];
      for (var i = 0; i < arr.length && out.length < MAX_LAYERS; i++) {
        var L = arr[i]; if (!L || typeof L !== 'object') continue;
        var src = abs(L.src || L.url || L.image, base); if (!src) continue;
        var z = clamp(num(L.z, out.length / Math.max(1, arr.length - 1)), 0, 1);
        var blend = (L.blend === 'add' || L.blend === 'additive') ? 'add' : 'normal';
        var drive = null;
        if (L.drive && typeof L.drive === 'object' && typeof L.drive.gain === 'string')
          drive = { gain: L.drive.gain,
                    min: clamp(num(L.drive.min, 0), 0, 4),
                    max: clamp(num(L.drive.max, 1), 0, 4) };
        out.push({
          id: (typeof L.id === 'string' && L.id) || ('l' + i),
          src: src,
          normal: abs(L.normal, base),
          z: z,
          par: num(L.par, 2 * z - 1),
          fit: (L.fit === 'full') ? 'full' : 'art',
          scale: clamp(num(L.scale, 1), 0.2, 2),
          relief: clamp(num(L.relief, 0), 0, 1),
          blend: blend,
          foil: !!L.foil,
          opacity: clamp(num(L.opacity, 1), 0, 1),
          drive: drive
        });
      }
      if (!out.length) return null;

      out.sort(function (a, b) { return a.z - b.z; });
      /* Defaults that need the whole stack to decide:
       *  · the bottom plate carries the relief unless somebody asked otherwise — a card with no
       *    embossing anywhere reads as printed paper, and the flat path always had some.
       *  · the bottom plate goes edge-to-edge unless told otherwise, so parallax cannot slide
       *    the backing off its own card. */
      var declared = out.some(function (l) { return l.relief > 0; });
      if (!declared) out[0].relief = 0.6;
      if (out[0].fit !== 'full' && !arr.some(function (l) { return l && l.fit; })) out[0].fit = 'full';

      return {
        v: VERSION,
        size: Array.isArray(raw.size) ? raw.size.slice(0, 2).map(function (n) { return num(n, 0); }) : null,
        title: typeof raw.title === 'string' ? raw.title : null,
        layers: out
      };
    } catch (e) { return null; }
  }

  /** `art/hero/34.webp` -> `art/hero/34.layers.json`. Purely a string swap; no request yet. */
  function sidecarUrl(artUrl) {
    if (!artUrl || typeof artUrl !== 'string') return null;
    try {
      var u = new URL(artUrl, (global.location && global.location.href) || 'https://x/');
      u.hash = ''; u.search = '';
      u.pathname = u.pathname.replace(/\.[a-z0-9]+$/i, '') + '.layers.json';
      return u.href;
    } catch (e) { return null; }
  }

  /**
   * @param artUrl  the flat art URL for this card (the sidecar is derived from it)
   * @param o       { url } explicit sidecar, or { inline } an already-parsed object
   * @returns Promise<spec|null> — **null is the normal answer** for every card today.
   */
  function load(artUrl, o) {
    o = o || {};
    if (o.inline) return Promise.resolve(normalize(o.inline, o.base || artUrl || (global.location || {}).href));
    var url = o.url || sidecarUrl(artUrl);
    if (!url || typeof fetch !== 'function') return Promise.resolve(null);
    return fetch(url, { cache: 'default' })
      .then(function (r) { return r && r.ok ? r.json() : null; })
      .then(function (j) { return normalize(j, url); })
      .catch(function () { return null; });      // 404 / blocked / bad JSON — all the same answer
  }

  global.CardLayers = {
    VERSION: VERSION, KINDS: KINDS, MAX_LAYERS: MAX_LAYERS,
    load: load, normalize: normalize, sidecarUrl: sidecarUrl
  };
})(typeof window !== 'undefined' ? window : globalThis);
