#!/usr/bin/env node
/* THE SHARE CABINET — build `play.html` from `riprocketer.html`.        node scripts/build-play.mjs
 *
 * Artist, 2026-10-07: *"how can we get riprocketer to play as an IN FEED POST ON TWITTER … someone
 * recently put the entire playable minecraft game on x."*
 *
 * ⛔ THE PREMISE WAS MEASURED AND IT IS NOT IN-FEED. Read as Twitterbot, the viral Minecraft post's
 *   site serves `twitter:card = summary_large_image` — a plain link card. You tap it and X opens
 *   the game in its IN-APP BROWSER; that is why players reported having to tap the post twice. The
 *   coverage calling it "embedded inside X" overstated it. **Which is the good news:** a link card
 *   needs no allowlist, no partnership and no approval, and it is what got ~2.5M views.
 *   True in-feed is `twitter:card = player`, historically allowlisted and documented as being for
 *   video. Worth submitting — it costs one meta tag — but it cannot be the plan.
 *
 * ⛔ SO THIS IS A GENERATOR, NOT A COPY, AND THAT IS THE WHOLE REASON IT IS A FILE. `restyle-backs.mjs`
 *   is this project's recorded failure: a hand-patched OUTPUT and a generator left armed to put the
 *   defect back. `riprocketer.html` is edited constantly — a hand-forked share page would be a
 *   second cabinet drifting quietly out of date on the one surface strangers arrive through.
 *   `npm run test:play` asserts this script's output IS the shipped file.
 *
 * WHAT IT CHANGES, and nothing else:
 *   1. `gate.js`   — the pre-launch veil. A stranger tapping in from a post would otherwise meet
 *                    `◈ PRIVATE · PRE-LAUNCH ◈` and a password field.
 *   2. `orient.js` — the "turn it sideways" veil. A feed hands you a PORTRAIT phone, and this is a
 *                    vertical shooter: you fly UP a facility. Portrait is its native shape, and
 *                    `js/rrpc-app.js` now frames the field's WIDTH when the viewport is tall.
 *   3. `wallet.js` — removed, and the same argument SuperRare's security team made about the
 *                    embed applies with more force here: a game arriving from a social post that
 *                    asks for a wallet is indistinguishable from a phish. ⚑ It needs no other
 *                    edit — every call site is guarded `window.RipWallet &&`, so `refreshGate`
 *                    hides the paid button and writes the practice note on its own.
 *   4. the card meta, which `riprocketer.html` has NONE of — shared today it renders as a bare URL.
 *   5. the start screen: eight rules become one line and one button. A reader scrolling a feed did
 *      not come for a manual.
 * ⚠ EVERY ID THE DRIVER TOUCHES SURVIVES. `$('startNote')` is written UNGUARDED (rrpc-app.js), so
 *   dropping it throws inside the gate refresh and the game never starts — the share build would
 *   fail in the one way nobody would see from the arcade.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://www.ripmaster3030studios.com';

/* ⚠ every replacement is asserted. A `.replace()` that matches nothing changes nothing and says
 * nothing — recorded in project memory as costing a whole round on `drops.seed()`. */
function cut(s, needle, with_, what) {
  if (!s.includes(needle)) throw new Error('build-play: anchor missing — ' + what);
  return s.replace(needle, with_);
}

export async function buildPlay() {
  let s = await readFile(join(ROOT, 'riprocketer.html'), 'utf8');

  // 1 · the head: title, card meta, and a note that this file is generated
  s = cut(s,
    '<title>RIP ROCKETER · ripmaster3030studios</title>\n' +
    '<meta name="description" content="Galaga on acid. A formation of trading cards flies in, breaks out and dives at you. Rip it back.">',
    '<title>RIP ROCKETER — play it here</title>\n' +
    '<meta name="description" content="Galaga on acid. A formation of trading cards flies in, breaks out and dives at you. Rip it back. Free, no sign-up, plays in the browser.">\n' +
    '<!-- ⛔ GENERATED BY scripts/build-play.mjs FROM riprocketer.html. Do not hand-edit: the next\n' +
    '     run silently reverts you, which is this project\'s recorded restyle-backs.mjs failure. -->\n' +
    '<link rel="canonical" href="' + SITE + '/play.html">\n' +
    '<!-- ⚑ THE CARD IS THE WHOLE DELIVERY MECHANISM. `summary_large_image` is what the viral\n' +
    '     Minecraft-on-X post actually used (verified off its own meta tags) — one tap from the\n' +
    '     feed opens the game full-screen in X\'s in-app browser. `player` would run it INSIDE the\n' +
    '     timeline but is historically allowlisted and documented as video-only. -->\n' +
    '<meta name="twitter:card" content="summary_large_image">\n' +
    '<meta name="twitter:title" content="RIP ROCKETER — Galaga on acid">\n' +
    '<meta name="twitter:description" content="A formation of trading cards flies in, breaks out and dives at you. Tap to fly. Free, no sign-up, no wallet.">\n' +
    '<meta name="twitter:image" content="' + SITE + '/media/site/play-card.png">\n' +
    '<meta name="twitter:image:alt" content="RIP ROCKETER — a formation of trading cards diving at a ship climbing a facility.">\n' +
    '<meta property="og:type" content="website">\n' +
    '<meta property="og:url" content="' + SITE + '/play.html">\n' +
    '<meta property="og:title" content="RIP ROCKETER — Galaga on acid">\n' +
    '<meta property="og:description" content="A formation of trading cards flies in, breaks out and dives at you. Tap to fly. Free, no sign-up, no wallet.">\n' +
    '<meta property="og:image" content="' + SITE + '/media/site/play-card.png">',
    'title + description');

  /* 2 · the modules a stranger arriving from a post must not meet.
   * ⛔ MATCHED BY SHAPE, NOT BY EXACT BYTES, and that is not tidiness — the first version pinned
   *   `'  <script src="/gate.js"></script>\n'` with its two leading spaces, and the very next
   *   merge from main unindented that tag while adding six modules. The generator stopped dead,
   *   which is the good outcome; a looser `.replace()` would have matched nothing, changed
   *   nothing, said nothing and shipped a share page with the pre-launch veil on it. This repo's
   *   recorded form of that lesson is the pack price: match a SHAPE, because a shape covers the
   *   spelling you did not think of. */
  s = dropScripts(s, [
    ['/gate.js', 'the pre-launch veil — a stranger would meet a password field'],
    ['js/orient.js', 'the "turn it sideways" veil, on the one orientation a feed guarantees'],
    ['js/wallet.js', 'no wallet on a surface reached from a social link'],
    /* ⚠ guarded (`root.RipWallet && …`) so it degrades rather than throwing — but a claim flow on
     * a page whose whole promise is "no sign-up, no wallet, nothing to buy" is the dead-control
     * failure this project already names: a button that goes nowhere is worse than no button. */
    ['js/hero-claim.js', 'the hero claim flow belongs on the real site, behind a wallet'],
  ]);

  // 4 · the start screen. One line, one button — a feed did not come for a manual.
  const rulesStart = s.indexOf('      <div class="rules">');
  const rulesEnd = s.indexOf('      <div class="keys-preview">');
  if (rulesStart < 0 || rulesEnd < 0 || rulesEnd < rulesStart) throw new Error('build-play: rules block not found');
  s = s.slice(0, rulesStart) +
    '      <!-- ⚑ EIGHT RULES BECAME ONE LINE. The arcade\'s visitor chose this cabinet; a reader\n' +
    '           scrolling a feed was handed it, and has about two seconds of patience. Everything\n' +
    '           cut is still taught where it is needed — the game names each verb the first time\n' +
    '           it happens, and the full rules live on riprocketer.html. -->\n' +
    '      <div class="rules">\n' +
    '        <div><b>TAP</b> to roll · <b>TAP TWICE</b> to dash · <b>HOLD</b> the second tap and your\n' +
    '        finger <i>draws the path</i>. You are always shooting.</div>\n' +
    '      </div>\n' +
    s.slice(rulesEnd);

  // 5 · the doors. The arcade is not where a stranger came from.
  s = cut(s,
    '      <div class="mininote"><a href="arcade.html">◄ back to the arcade</a></div>',
    '      <div class="mininote"><a href="' + SITE + '/arcade.html">five more games ▸</a> · ' +
    '<a href="' + SITE + '/">ripmaster3030studios</a></div>\n' +
    '      <div class="mininote" style="opacity:.6">Free to play. No sign-up, no wallet, nothing to buy. ' +
    'An experimental art project — <b>NFA</b>.</div>',
    'arcade door');
  s = cut(s,
    '      <div class="mininote"><a href="arcade.html">◄ arcade</a> · <a href="index.html">the pack</a></div>',
    '      <div class="mininote"><a href="' + SITE + '/arcade.html">five more games ▸</a> · ' +
    '<a href="' + SITE + '/">ripmaster3030studios</a></div>',
    'over-screen door');

  // 6 · the logo. 819 KB of already-compressed PNG, `fetchpriority="high"`, in front of someone
  //     who arrived from a feed. `scripts/build-play-card.mjs` re-encodes it to WebP with its
  //     black plate baked into real alpha — 58% off, and it no longer needs a blend mode to
  //     composite, which is what put a hard black box on the first two share cards.
  s = s.split('src="riprocketer.png"').join('src="media/site/riprocketer.webp"');
  if (s.includes('src="riprocketer.png"')) throw new Error('build-play: logo not repointed');

  return s;
}

/* ── feed.html — THE PLAYER CARD, i.e. the literal in-feed ask ───────────────────────────────
 * Artist, after posting `play.html`: *"not playing in feed"* · *"clicking it takes you to the site"*.
 * Correct, and the card was doing exactly what a `summary_large_image` can do. The only mechanism
 * that renders a running page INSIDE the timeline is `twitter:card = player`, which frames a URL
 * you nominate at a size you declare.
 *
 * ⚑ THE HARD HALF IS ALREADY PROVEN, AND IT IS THE HALF NOBODY CHECKS. Driven at 480×480 in a
 *   genuine cross-origin iframe AND in a sandboxed one at an opaque origin — the worst case, where
 *   `localStorage` THROWS and every same-origin fetch fails — this game boots, reaches `play`,
 *   frames the whole ±6.3 field (hw 6.68, horizontally, so the portrait fix carries to a square),
 *   puts the ship on screen at BOTH field edges, answers a real touch drag (ship 0.00 → 3.52, one
 *   roll registered) and throws nothing. Every localStorage touch on this path was already inside
 *   a try/catch and `theme.js` already bails on `window.self !== window.top`. **A player card that
 *   X renders would work.** `npm run test:play` §7 is that measurement, kept.
 *
 * ⛔ WHETHER X RENDERS IT IS NOT OURS TO DECIDE, AND THIS FILE MUST NOT PRETEND OTHERWISE. The
 *   player card is historically allowlisted per domain and X's own Cards documentation is gone, so
 *   there is no current reference to check against and no approval we can self-serve. The honest
 *   position: it costs four meta tags, it cannot make anything worse, and it may simply be ignored.
 *
 * ⛔ WHICH IS WHY THIS IS A SEPARATE FILE AND `play.html` IS UNTOUCHED. The link card is POSTED and
 *   WORKING — changing its card type to gamble on an allowlist would put the one proven surface at
 *   risk to chase an unproven one. Two files, two cards, and the already-shared URL keeps behaving
 *   exactly as it does today.
 * ⚑ It is DERIVED from buildPlay() rather than parallel to it, so the share build has one set of
 *   anchors and cannot drift into two cabinets — `restyle-backs.mjs`, again.
 * ⚠ `twitter:image` STAYS. X's own docs name it the fallback for clients that cannot render the
 *   iframe, so an ignored player card degrades to the large-image card we already ship rather than
 *   to nothing. That is the whole reason this is safe to post.
 * ⚠ The player points at THIS page. X's guidance is that a player URL be a bare page rather than a
 *   site — and that is what this already is: the game, full screen, no chrome. */
const FEED = 480;   // square. Measured good at 480×480; the field frames by WIDTH at that aspect.

/* ⛔ THE SCRIPTS A STRANGER IN A TIMELINE MUST NOT MEET, matched by SHAPE. Shared by every share
 * build, because the list is a POLICY and three copies of a policy is how one of them drifts. */
function dropScripts(s, list) {
  for (const [src, why] of list) {
    const re = new RegExp('[ \\t]*<script src="' + src.replace(/[/.]/g, '\\$&') + '"[^>]*></script>\\n?');
    if (!re.test(s)) throw new Error('build-play: no <script src="' + src + '"> to drop — ' + why);
    s = s.replace(re, '');
  }
  return s;
}

export async function buildFeed() {
  let s = await buildPlay();

  s = cut(s,
    '<title>RIP ROCKETER — play it here</title>',
    '<title>RIP ROCKETER — play it in the post</title>',
    'feed title');

  s = cut(s,
    '<link rel="canonical" href="' + SITE + '/play.html">',
    '<link rel="canonical" href="' + SITE + '/feed.html">',
    'feed canonical');

  s = cut(s,
    '<!-- ⚑ THE CARD IS THE WHOLE DELIVERY MECHANISM. `summary_large_image` is what the viral\n' +
    '     Minecraft-on-X post actually used (verified off its own meta tags) — one tap from the\n' +
    '     feed opens the game full-screen in X\'s in-app browser. `player` would run it INSIDE the\n' +
    '     timeline but is historically allowlisted and documented as video-only. -->\n' +
    '<meta name="twitter:card" content="summary_large_image">',
    '<!-- ⚑ THE PLAYER CARD — the only mechanism that runs a page INSIDE the X timeline. Proven to\n' +
    '     survive the frame: driven at 480×480 cross-origin AND sandboxed at an opaque origin, this\n' +
    '     game boots, plays, frames the whole field and answers touch, with nothing thrown.\n' +
    '     ⛔ Whether X RENDERS it is gated per domain and not ours to decide. `twitter:image` below\n' +
    '     is X\'s documented fallback, so an ignored player card degrades to the same large-image\n' +
    '     card `play.html` ships — which is what makes this safe to post. -->\n' +
    '<meta name="twitter:card" content="player">\n' +
    '<meta name="twitter:player" content="' + SITE + '/feed.html">\n' +
    '<meta name="twitter:player:width" content="' + FEED + '">\n' +
    '<meta name="twitter:player:height" content="' + FEED + '">',
    'feed card type');

  s = s.split(SITE + '/play.html').join(SITE + '/feed.html');
  if (s.includes('/play.html')) throw new Error('build-play: a play.html url survived into feed.html');

  return s;
}

/* ── s9feed.html — SECTION 9 in the frame ───────────────────────────────────────────────────
 * Artist, 2026-10-07: *"now lets try the first person shooter game."*
 *
 * ⛔ THE WALLET IS NOT IN HERE, AND ONE MEASUREMENT DECIDES HALF OF IT BEFORE ANY ARGUMENT DOES:
 *   driven in both frame modes, `window.ethereum` is **false**. Injected wallets do not inject
 *   into third-party iframes, so MetaMask and everything like it is structurally unreachable from
 *   a timeline whatever we ship. WalletConnect could not be tested from this container (Chromium
 *   cannot reach esm.sh through the agent proxy, while curl can — a confounded result, recorded
 *   as inconclusive rather than used as evidence).
 * ⛔ The other half is the reason this repo has refused it twice, once on SuperRare's security
 *   team's explicit flag: **a frame that asks for a wallet is indistinguishable from a frame that
 *   has been swapped for a malicious one**, and teaching people that embedded art asking for a
 *   wallet is normal is the exact reflex phishing needs. An X timeline is the strongest available
 *   version of that. So: PLAY in the frame, CONNECT on the tap-through, where `section9.html`'s
 *   seat flow already lives and already works.
 *
 * ⚑ THE WAGER PANEL IS HIDDEN, NEVER REMOVED, and that is this project's own recorded rule rather
 *   than laziness — `cards/card-stage.js` keeps the flat card in the document because the page's
 *   data plumbing is written against its ids. Measured here before writing a line: `js/s9pc-ui.js`
 *   writes to `btnAnte` (3 refs), `cardsInfo` (3), `potLine`, `roster`, `cardGrid`, `anteVal`,
 *   `cardsVal`, `pickN`, `buildNote` and `lobNote`, and calls `RipNet.join()` UNGUARDED. Deleting
 *   the panel would throw inside the lobby and the cabinet would never start — the share build
 *   failing in the one way nobody would see from the arcade.
 * ⚠ So the ante, the card-staking grid, the pot, the roster and the seat box go dark by CSS. What
 *   is left is the one free door: Practice deathmatch. A stranger in a feed has nothing staked and
 *   nothing to stake.
 */
export async function buildS9Feed() {
  let s = await readFile(join(ROOT, 'section9.html'), 'utf8');

  s = cut(s,
    '<title>SECTION 9 TASKFORCE: SUPERGAME · ripmaster3030studios</title>',
    '<title>SECTION 9 — play it in the post</title>\n' +
    '<!-- ⛔ GENERATED BY scripts/build-play.mjs FROM section9.html. Do not hand-edit: the next\n' +
    '     run silently reverts you, which is this project\'s recorded restyle-backs.mjs failure. -->\n' +
    '<link rel="canonical" href="' + SITE + '/s9feed.html">\n' +
    '<!-- ⚑ THE PLAYER CARD. Renders in the timeline on DESKTOP; X\'s native mobile apps put it in\n' +
    '     the tweet detail view instead and open the player in their in-app browser on a tap, which\n' +
    '     is X\'s behaviour and not something this page can change. `twitter:image` is the\n' +
    '     documented fallback, so an ignored card degrades to a large-image card rather than to\n' +
    '     nothing. -->\n' +
    '<meta name="twitter:card" content="player">\n' +
    '<meta name="twitter:player" content="' + SITE + '/s9feed.html">\n' +
    '<meta name="twitter:player:width" content="' + FEED + '">\n' +
    '<meta name="twitter:player:height" content="' + FEED + '">\n' +
    '<meta name="twitter:title" content="SECTION 9 — taskforce supergame">\n' +
    '<meta name="twitter:description" content="Drop into a walled arena and rack up frags. Free practice, no sign-up, no wallet.">\n' +
    '<meta name="twitter:image" content="' + SITE + '/media/site/s9-card.png">\n' +
    '<meta name="twitter:image:alt" content="SECTION 9 — an operative in a walled arena.">\n' +
    '<meta property="og:type" content="website">\n' +
    '<meta property="og:url" content="' + SITE + '/s9feed.html">\n' +
    '<meta property="og:title" content="SECTION 9 — taskforce supergame">\n' +
    '<meta property="og:description" content="Drop into a walled arena and rack up frags. Free practice, no sign-up, no wallet.">\n' +
    '<meta property="og:image" content="' + SITE + '/media/site/s9-card.png">',
    's9 title + card meta');

  s = dropScripts(s, [
    ['gate.js', 'the pre-launch veil — a stranger would meet a password field'],
    /* ⛔ THE ONE THAT DECIDES WHETHER THIS IS REACHABLE AT ALL. SECTION 9 is one of the five
     * genuinely-wide cabinets that KEEP the "turn it sideways" veil, and a player card is a
     * SQUARE — so in a timeline that veil is an undismissable dead end over the whole game. */
    ['js/orient.js', 'the "turn it sideways" veil, over a square frame, with no way past it'],
    ['js/wallet.js', 'no wallet on a surface reached from a social post — see the block above'],
    ['js/wallet-ui.js', 'the connect button goes with the wallet it drives'],
    /* ⚠ session.js asks for a SIGNATURE (SIWE). A frame in somebody else\'s timeline asking a
     * visitor to sign a message is the phishing reflex in its purest form. */
    ['js/session.js', 'the seat flow SIGNS a message — never from inside a frame'],
    ['js/hero-claim.js', 'minting belongs on the real site, behind a wallet'],
    ['js/eth-play.js', 'the arcade fee takes real money on Base'],
  ]);

  /* ⚑ HIDDEN, NOT REMOVED — see the block above. One stylesheet, every id still in the document. */
  s = cut(s,
    '<link rel="icon" href="favicon.svg" type="image/svg+xml">',
    '<link rel="icon" href="favicon.svg" type="image/svg+xml">\n' +
    '<style>\n' +
    '  /* ⛔ THE WAGER HALF OF THE LOBBY GOES DARK, AND EVERY ELEMENT STAYS IN THE DOCUMENT.\n' +
    '     js/s9pc-ui.js writes to btnAnte, cardsInfo, potLine, roster, cardGrid, anteVal, cardsVal,\n' +
    '     pickN, buildNote and lobNote — measured, not assumed — so removing them throws inside the\n' +
    '     lobby and the cabinet never starts. `display:none` keeps every write landing somewhere.\n' +
    '     What is left is the one door a stranger can actually walk through: free practice. */\n' +
    '  #ovLobby .wbox, #ovLobby .pot, #ovLobby .roster,\n' +
    '  #ovLobby #seatBox, #ovLobby #arenaLobby, #ovLobby #btnAnte { display: none !important; }\n' +
    '  /* ⛔ AND #lobNote GOES WITH THEM, which is the sharpest one and was found by LOOKING at the\n' +
    '     frame rather than by reading the diff. js/s9pc-ui.js:156 picks that line off wallet state:\n' +
    '     with RipWallet gone the `!(Wt && Wt.hasWallet())` branch fires and the page tells a\n' +
    '     stranger scrolling a timeline to **"Connect a wallet (sign the ledger) to ante real\n' +
    '     $3030"** — an instruction with nothing behind it, on the one surface where asking for a\n' +
    '     wallet is indistinguishable from a phish. A dead control is worse than an absent one.\n' +
    '     ⚠ The ELEMENT stays (the driver writes to it); only the box goes. */\n' +
    '  #ovLobby #lobNote { display: none !important; }\n' +
    '  /* ⚠ the panel was running off the right edge at 480 — a cabinet-width box in a square\n' +
    '     frame. Measured clipped before this. */\n' +
    '  #ovLobby .panel { box-sizing: border-box; max-width: 100%; overflow-wrap: anywhere; }\n' +
    '  /* the practice button is the ONLY button now, so it reads as primary rather than as the\n' +
    '     lesser of two. `.alt` is the secondary skin it was wearing underneath the ante. */\n' +
    '  #ovLobby #btnPractice.alt { opacity: 1; }\n' +
    '  /* ⚠ a 480×480 frame is a SMALL panel. The lobby was authored for a cabinet and its logo\n' +
    '     alone ran to most of the frame — measured clipped at 480. */\n' +
    '  #ovLobby .panel { padding: 14px 12px; }\n' +
    '  #ovLobby h1 img { width: min(84%, 320px) !important; }\n' +
    '  #ovLobby .sub { font-size: 13px; line-height: 1.45; }\n' +
    '  /* ⛔ THE CONTROLS CARD IS 1,085px TALL IN A 480px FRAME — measured — so the start button\n' +
    '     sits 2.3 screens down. ⚠ It is NOT unreachable: #gh-ov is overflow-y:auto and scrolling\n' +
    '     to the bottom brings the button to y369, on screen. I nearly filed that as blade.html\'s\n' +
    '     recorded "BEGIN was off the bottom of the phone" bug and it is not — reading a position\n' +
    '     at scroll 0 and calling it off-screen is this repo\'s most-repeated probe mistake.\n' +
    '     ⚑ What IS true is the funnel argument index.html was rebuilt on: a reader handed a game\n' +
    '     by a feed has about two seconds, and 2.3 screens of control rows before the one button\n' +
    '     is the "first pressable action 3,516px down" failure at frame scale. The action goes\n' +
    '     above the fold, the detail under it — so the start button is PINNED and the controls\n' +
    '     scroll behind it. Nothing is removed; the controls still matter for a two-thumb FPS. */\n' +
    '  #gh-ov .gh-start { position: sticky; bottom: 6px; z-index: 2;\n' +
    '    box-shadow: 0 6px 22px rgba(2,4,10,.95), 0 0 0 6px rgba(2,4,10,.75); }\n' +
    '</style>',
    's9 feed stylesheet');

  /* ⛔ AND THE COPY HAD TO FOLLOW THE UI, or the page describes a game it does not offer. The
   * cabinet's own line sells the WAGER — "everyone antes $3030 and stakes cards into one pot" —
   * and this build has no ante, no staking and no pot. This repo already names that failure on
   * the arcade shelf: a description where somebody decides what to open is a PROMISE, and THE
   * CITY's card promised a photo mode that was never built. The free match is the whole offer
   * here, so it is the whole sentence. */
  s = cut(s,
    '      <div class="sub">Drop into a <b>walled arena</b> and rack up frags. Everyone antes <b>$3030</b> and stakes cards into one pot — <b>most frags when the clock runs out</b> takes everything. Infinite respawns; a death is a setback, not the end.</div>',
    '      <div class="sub">Drop into a <b>walled arena</b> and rack up frags. Infinite respawns — ' +
    'a death is a setback, not the end. <b>Free practice, nothing staked.</b></div>',
    's9 lobby copy');

  // the doors: absolute, because this page is opened from somewhere that is not this site
  s = cut(s,
    '      <div class="mininote"><a href="arcade.html">the arcade</a> · <a href="index.html">the pack</a></div>',
    '      <div class="mininote"><a href="' + SITE + '/arcade.html">six more games ▸</a> · ' +
    '<a href="' + SITE + '/">ripmaster3030studios</a></div>\n' +
    '      <div class="mininote" style="opacity:.6">Free to play. No sign-up, no wallet, nothing to buy. ' +
    'An experimental art project — <b>NFA</b>.</div>',
    's9 lobby doors');

  return s;
}

/* ⛔ ONLY WRITE WHEN RUN DIRECTLY. `test:play` imports `buildPlay()` to assert the shipped file
 * IS this script's output — and if importing it WROTE that file first, the comparison would
 * write-then-compare and pass on every build, including a drifted one. That is the tautology
 * this project already shipped once in the claim-signer guard: a test whose only failing edit
 * is an edit to the test. */
if (import.meta.url === pathToFileURL(process.argv[1] || '').href) {
  for (const [name, fn] of [['play.html', buildPlay], ['feed.html', buildFeed],
                            ['s9feed.html', buildS9Feed]]) {
    const out = await fn();
    await writeFile(join(ROOT, name), out, 'utf8');
    console.log('✦ ' + name.padEnd(10) + ' (' + (out.length / 1024).toFixed(1) + ' KB)');
  }
}
