#!/usr/bin/env node
/* THE SHARE CABINET — build `play.html` from `riprocketer.html`.        node scripts/build-play.mjs
 *
 * Artist, 2026-10-07: *"how can we get riprocketer to play as an IN FEED POST ON TWITTER … someone
 * recently put the entire playable minecraft game on x."*
 *
 * ⛔ THE PREMISE WAS MEASURED AND IT IS NOT IN-FEED. Read as Twitterbot, the viral Minecraft post's
 *   site serves `twitter:card = summary_large_image` — a plain link card. You tap it and X opens
 *   the game in its IN-APP BROWSER; that is why players reported having to tap the post twice. The
 *   coverage calling it "embedded inside X" overstated it. **Which is the good news:** a link card
 *   needs no allowlist, no partnership and no approval, and it is what got ~2.5M views.
 *   True in-feed is `twitter:card = player`, historically allowlisted and documented as being for
 *   video. Worth submitting — it costs one meta tag — but it cannot be the plan.
 *
 * ⛔ SO THIS IS A GENERATOR, NOT A COPY, AND THAT IS THE WHOLE REASON IT IS A FILE. `restyle-backs.mjs`
 *   is this project's recorded failure: a hand-patched OUTPUT and a generator left armed to put the
 *   defect back. `riprocketer.html` is edited constantly — a hand-forked share page would be a
 *   second cabinet drifting quietly out of date on the one surface strangers arrive through.
 *   `npm run test:play` asserts this script's output IS the shipped file.
 *
 * WHAT IT CHANGES, and nothing else:
 *   1. `gate.js`   — the pre-launch veil. A stranger tapping in from a post would otherwise meet
 *                    `◈ PRIVATE · PRE-LAUNCH ◈` and a password field.
 *   2. `orient.js` — the "turn it sideways" veil. A feed hands you a PORTRAIT phone, and this is a
 *                    vertical shooter: you fly UP a facility. Portrait is its native shape, and
 *                    `js/rrpc-app.js` now frames the field's WIDTH when the viewport is tall.
 *   3. `wallet.js` — removed, and the same argument SuperRare's security team made about the
 *                    embed applies with more force here: a game arriving from a social post that
 *                    asks for a wallet is indistinguishable from a phish. ⚑ It needs no other
 *                    edit — every call site is guarded `window.RipWallet &&`, so `refreshGate`
 *                    hides the paid button and writes the practice note on its own.
 *   4. the card meta, which `riprocketer.html` has NONE of — shared today it renders as a bare URL.
 *   5. the start screen: eight rules become one line and one button. A reader scrolling a feed did
 *      not come for a manual.
 * ⚠ EVERY ID THE DRIVER TOUCHES SURVIVES. `$('startNote')` is written UNGUARDED (rrpc-app.js), so
 *   dropping it throws inside the gate refresh and the game never starts — the share build would
 *   fail in the one way nobody would see from the arcade.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://www.ripmaster3030studios.com';

/* ⚠ every replacement is asserted. A `.replace()` that matches nothing changes nothing and says
 * nothing — recorded in project memory as costing a whole round on `drops.seed()`. */
function cut(s, needle, with_, what) {
  if (!s.includes(needle)) throw new Error('build-play: anchor missing — ' + what);
  return s.replace(needle, with_);
}

export async function buildPlay() {
  let s = await readFile(join(ROOT, 'riprocketer.html'), 'utf8');

  // 1 · the head: title, card meta, and a note that this file is generated
  s = cut(s,
    '<title>RIP ROCKETER · ripmaster3030studios</title>\n' +
    '<meta name="description" content="Galaga on acid. A formation of trading cards flies in, breaks out and dives at you. Rip it back.">',
    '<title>RIP ROCKETER — play it here</title>\n' +
    '<meta name="description" content="Galaga on acid. A formation of trading cards flies in, breaks out and dives at you. Rip it back. Free, no sign-up, plays in the browser.">\n' +
    '<!-- ⛔ GENERATED BY scripts/build-play.mjs FROM riprocketer.html. Do not hand-edit: the next\n' +
    '     run silently reverts you, which is this project\'s recorded restyle-backs.mjs failure. -->\n' +
    '<link rel="canonical" href="' + SITE + '/play.html">\n' +
    '<!-- ⚑ THE CARD IS THE WHOLE DELIVERY MECHANISM. `summary_large_image` is what the viral\n' +
    '     Minecraft-on-X post actually used (verified off its own meta tags) — one tap from the\n' +
    '     feed opens the game full-screen in X\'s in-app browser. `player` would run it INSIDE the\n' +
    '     timeline but is historically allowlisted and documented as video-only. -->\n' +
    '<meta name="twitter:card" content="summary_large_image">\n' +
    '<meta name="twitter:title" content="RIP ROCKETER — Galaga on acid">\n' +
    '<meta name="twitter:description" content="A formation of trading cards flies in, breaks out and dives at you. Tap to fly. Free, no sign-up, no wallet.">\n' +
    '<meta name="twitter:image" content="' + SITE + '/media/site/play-card.png">\n' +
    '<meta name="twitter:image:alt" content="RIP ROCKETER — a formation of trading cards diving at a ship climbing a facility.">\n' +
    '<meta property="og:type" content="website">\n' +
    '<meta property="og:url" content="' + SITE + '/play.html">\n' +
    '<meta property="og:title" content="RIP ROCKETER — Galaga on acid">\n' +
    '<meta property="og:description" content="A formation of trading cards flies in, breaks out and dives at you. Tap to fly. Free, no sign-up, no wallet.">\n' +
    '<meta property="og:image" content="' + SITE + '/media/site/play-card.png">',
    'title + description');

  /* 2 · the modules a stranger arriving from a post must not meet.
   * ⛔ MATCHED BY SHAPE, NOT BY EXACT BYTES, and that is not tidiness — the first version pinned
   *   `'  <script src="/gate.js"></script>\n'` with its two leading spaces, and the very next
   *   merge from main unindented that tag while adding six modules. The generator stopped dead,
   *   which is the good outcome; a looser `.replace()` would have matched nothing, changed
   *   nothing, said nothing and shipped a share page with the pre-launch veil on it. This repo's
   *   recorded form of that lesson is the pack price: match a SHAPE, because a shape covers the
   *   spelling you did not think of. */
  for (const [src, why] of [
    ['/gate.js', 'the pre-launch veil — a stranger would meet a password field'],
    ['js/orient.js', 'the "turn it sideways" veil, on the one orientation a feed guarantees'],
    ['js/wallet.js', 'no wallet on a surface reached from a social link'],
    /* ⚠ guarded (`root.RipWallet && …`) so it degrades rather than throwing — but a claim flow on
     * a page whose whole promise is "no sign-up, no wallet, nothing to buy" is the dead-control
     * failure this project already names: a button that goes nowhere is worse than no button. */
    ['js/hero-claim.js', 'the hero claim flow belongs on the real site, behind a wallet'],
  ]) {
    const re = new RegExp('[ \\t]*<script src="' + src.replace(/[/.]/g, '\\$&') + '"[^>]*></script>\\n?');
    if (!re.test(s)) throw new Error('build-play: no <script src="' + src + '"> to drop — ' + why);
    s = s.replace(re, '');
  }

  // 4 · the start screen. One line, one button — a feed did not come for a manual.
  const rulesStart = s.indexOf('      <div class="rules">');
  const rulesEnd = s.indexOf('      <div class="keys-preview">');
  if (rulesStart < 0 || rulesEnd < 0 || rulesEnd < rulesStart) throw new Error('build-play: rules block not found');
  s = s.slice(0, rulesStart) +
    '      <!-- ⚑ EIGHT RULES BECAME ONE LINE. The arcade\'s visitor chose this cabinet; a reader\n' +
    '           scrolling a feed was handed it, and has about two seconds of patience. Everything\n' +
    '           cut is still taught where it is needed — the game names each verb the first time\n' +
    '           it happens, and the full rules live on riprocketer.html. -->\n' +
    '      <div class="rules">\n' +
    '        <div><b>TAP</b> to roll · <b>TAP TWICE</b> to dash · <b>HOLD</b> the second tap and your\n' +
    '        finger <i>draws the path</i>. You are always shooting.</div>\n' +
    '      </div>\n' +
    s.slice(rulesEnd);

  // 5 · the doors. The arcade is not where a stranger came from.
  s = cut(s,
    '      <div class="mininote"><a href="arcade.html">◄ back to the arcade</a></div>',
    '      <div class="mininote"><a href="' + SITE + '/arcade.html">five more games ▸</a> · ' +
    '<a href="' + SITE + '/">ripmaster3030studios</a></div>\n' +
    '      <div class="mininote" style="opacity:.6">Free to play. No sign-up, no wallet, nothing to buy. ' +
    'An experimental art project — <b>NFA</b>.</div>',
    'arcade door');
  s = cut(s,
    '      <div class="mininote"><a href="arcade.html">◄ arcade</a> · <a href="index.html">the pack</a></div>',
    '      <div class="mininote"><a href="' + SITE + '/arcade.html">five more games ▸</a> · ' +
    '<a href="' + SITE + '/">ripmaster3030studios</a></div>',
    'over-screen door');

  // 6 · the logo. 819 KB of already-compressed PNG, `fetchpriority="high"`, in front of someone
  //     who arrived from a feed. `scripts/build-play-card.mjs` re-encodes it to WebP with its
  //     black plate baked into real alpha — 58% off, and it no longer needs a blend mode to
  //     composite, which is what put a hard black box on the first two share cards.
  s = s.split('src="riprocketer.png"').join('src="media/site/riprocketer.webp"');
  if (s.includes('src="riprocketer.png"')) throw new Error('build-play: logo not repointed');

  return s;
}

/* ⛔ ONLY WRITE WHEN RUN DIRECTLY. `test:play` imports `buildPlay()` to assert the shipped file
 * IS this script's output — and if importing it WROTE that file first, the comparison would
 * write-then-compare and pass on every build, including a drifted one. That is the tautology
 * this project already shipped once in the claim-signer guard: a test whose only failing edit
 * is an edit to the test. */
if (import.meta.url === pathToFileURL(process.argv[1] || '').href) {
  const out = await buildPlay();
  await writeFile(join(ROOT, 'play.html'), out, 'utf8');
  console.log('✦ play.html  (' + (out.length / 1024).toFixed(1) + ' KB)');
}
