#!/usr/bin/env node
/* Flatten a contract and its imports into ONE file that can be pasted into Remix.
 *
 *   node scripts/flatten.mjs contracts/Ripmaster3030Lens721.sol
 *
 * Why this exists: deploying from Remix means the private key never leaves MetaMask —
 * no key in a shell, no key in an env var, no key in a script's memory. For a contract
 * that will hold 33 1/1s that is the right trade, and Remix wants a single file.
 *
 * Resolves imports depth-first, emits each file once, keeps a single SPDX line and a single
 * pragma at the top (Solidity rejects repeats). Verifies the flattened output compiles to the
 * same EXECUTABLE bytecode as the original before writing — a flattener that silently drops a
 * file would otherwise produce something that looks fine and isn't.
 *
 * The comparison ignores the trailing CBOR metadata block. solc appends a hash of the
 * metadata JSON, and that JSON lists source paths — so flattening changes it by construction.
 * Identical executable code with a different metadata hash is expected and fine; a difference
 * anywhere BEFORE the metadata is a real defect and aborts.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, dirname, resolve as pres } from 'node:path';
import { fileURLToPath } from 'node:url';
import solc from 'solc';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const entry = process.argv[2] || 'contracts/Ripmaster3030Lens721.sol';
const outDir = join(ROOT, 'contracts', 'build');

function resolvePath(spec, fromDir) {
  const cands = spec.startsWith('.')
    ? [pres(fromDir, spec)]
    : [join(ROOT, 'node_modules', spec), join(ROOT, spec)];
  for (const c of cands) if (existsSync(c)) return c;
  throw new Error(`cannot resolve import ${spec} (from ${fromDir})`);
}

const seen = new Set();
const chunks = [];
let pragma = null;

function walk(absPath) {
  if (seen.has(absPath)) return;
  seen.add(absPath);
  const src = readFileSync(absPath, 'utf8');
  const dir = dirname(absPath);
  for (const m of src.matchAll(/^\s*import\s+(?:\{[^}]*\}\s+from\s+)?["']([^"']+)["']\s*;/gm)) {
    walk(resolvePath(m[1], dir));                    // depth-first: dependencies emitted first
  }
  // The ENTRY file's pragma wins. Depth-first means dependencies are visited first, so
  // taking the first pragma seen would inherit OpenZeppelin's looser ^0.8.20 and invite
  // Remix to compile our ^0.8.24 contract on an older compiler.
  if (absPath === join(ROOT, entry)) {
    const m = src.match(/^\s*pragma solidity ([^;]+);/m);
    if (m) pragma = m[1].trim();
  }
  const body = src
    .replace(/^\s*import\s+(?:\{[^}]*\}\s+from\s+)?["'][^"']+["']\s*;\s*$/gm, '')
    .replace(/^\s*\/\/ SPDX-License-Identifier:.*$/gm, '')
    .replace(/^\s*pragma solidity [^;]+;\s*$/gm, '');
  chunks.push(`// ─── ${absPath.replace(ROOT + '/', '')} ───\n${body.trim()}\n`);
}

walk(join(ROOT, entry));
const flat = `// SPDX-License-Identifier: MIT\npragma solidity ${pragma};\n\n` +
  `// FLATTENED — generated by scripts/flatten.mjs from ${entry}\n` +
  `// ${seen.size} source files. Do not edit; edit the originals and regenerate.\n\n` +
  chunks.join('\n');

// ── the check that makes this trustworthy: same bytecode as the unflattened build ──
function build(sources) {
  const findImport = p => {
    for (const c of [join(ROOT, 'node_modules', p), join(ROOT, p)]) if (existsSync(c)) return { contents: readFileSync(c, 'utf8') };
    return { error: 'not found: ' + p };
  };
  const out = JSON.parse(solc.compile(JSON.stringify({
    language: 'Solidity', sources,
    settings: { optimizer: { enabled: true, runs: 200 }, viaIR: true, outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object'] } } },
  }), { import: findImport }));
  const errs = (out.errors || []).filter(e => e.severity === 'error');
  if (errs.length) { errs.forEach(e => console.error(e.formattedMessage)); process.exit(1); }
  return out;
}

const name = entry.split('/').pop().replace('.sol', '');
const orig = build({ [entry]: { content: readFileSync(join(ROOT, entry), 'utf8') } }).contracts[entry][name];
const flatOut = build({ 'flat.sol': { content: flat } }).contracts['flat.sol'][name];

/* Strip the trailing CBOR metadata (…a264 69706673 5822 <hash> 64736f6c63 …) and compare
 * only the code the EVM will actually run. */
const stripMeta = hex => { const i = hex.lastIndexOf('a2646970667358'); return i < 0 ? hex : hex.slice(0, i); };
const codeA = stripMeta(orig.evm.bytecode.object), codeB = stripMeta(flatOut.evm.bytecode.object);
const same = codeA === codeB;
const metaDiffers = orig.evm.bytecode.object !== flatOut.evm.bytecode.object;
console.log(`sources flattened : ${seen.size}`);
console.log(`bytecode          : ${(flatOut.evm.bytecode.object.length / 2).toLocaleString()} bytes`);
console.log(`executable code   : ${same ? '✓ identical to the unflattened build' : '✗ DIFFERS — do not use'}`);
if (same && metaDiffers) console.log(`metadata hash     : differs, as expected (it hashes source paths)`);
if (!same) {
  let i = 0; while (i < codeA.length && codeA[i] === codeB[i]) i++;
  console.error(`\nfirst divergence at nibble ${i} of ${codeA.length} (${((i / codeA.length) * 100).toFixed(1)}% in)`);
  console.error('orig:', codeA.slice(i, i + 64));
  console.error('flat:', codeB.slice(i, i + 64));
  process.exit(1);
}

mkdirSync(outDir, { recursive: true });
const flatPath = join(outDir, `${name}.flat.sol`);
writeFileSync(flatPath, flat);
writeFileSync(join(outDir, `${name}.abi.json`), JSON.stringify(orig.abi, null, 1));
console.log(`\n✦ ${flatPath.replace(ROOT + '/', '')}`);
console.log(`✦ contracts/build/${name}.abi.json`);
