#!/usr/bin/env node
/* upperdeckripmaster3030 — morph-mesh: generate new creature iterations from a mesh.
 *
 * Runs RoninMorph (the same seeded distortion the game uses as a card lens) over an OBJ and
 * writes out new OBJs. Because the morph is deterministic, a seed IS the identity of an
 * iteration — re-run with the same seed and you get the same creature back, byte for byte.
 * That makes this usable as an authoring tool: sweep seeds, keep the ones you like, and the
 * kept ones are reproducible forever from just their name.
 *
 * Per-part structure is preserved (each `o` block stays its own object), so a morphed file
 * still drops straight into models/ and attaches to the fighter skeleton by part name.
 *
 *   node scripts/morph-mesh.mjs <in.obj> <outDir> [--seeds a,b,c] [--amt 0.7] [--ops melt,twist]
 *
 * Examples
 *   node scripts/morph-mesh.mjs TROOPER.obj out --seeds ripmaster,cosmic-yawn,blue-boar
 *   node scripts/morph-mesh.mjs Mom.obj out --ops sag,bulge,static --amt 0.85
 *
 * NOTE: distorting a mesh does not change who owns it. Only run this on geometry you own or
 * that is clearly licensed for commercial/NFT use — a morphed copyrighted character is still
 * a derivative work.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { basename, join } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __dir = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dir, '..');

// load the browser modules in a tiny shim so the tool and the game share ONE implementation
const shim = { window: {} };
const load = f => { const src = readFileSync(join(ROOT, 'js', f), 'utf8'); new Function('window', src)(shim.window); };
load('ronin-morph.js'); load('ronin-obj.js');
const { RoninMorph, RoninOBJ } = shim.window;

// ── args ──────────────────────────────────────────────────────────────────────
const argv = process.argv.slice(2);
if (argv.length < 2) { console.error('usage: morph-mesh.mjs <in.obj> <outDir> [--seeds a,b,c] [--amt 0.7] [--ops op,op]'); process.exit(1); }
const inPath = argv[0], outDir = argv[1];
const flag = n => { const i = argv.indexOf('--' + n); return i > 0 ? argv[i + 1] : null; };
const seeds = (flag('seeds') || 'ripmaster').split(',').map(s => s.trim()).filter(Boolean);
const amt = parseFloat(flag('amt') || '0.7');
const opList = flag('ops') ? flag('ops').split(',').map(s => s.trim()).filter(Boolean) : null;
const keepProps = argv.includes('--keep-props');
// stage furniture that isn't part of the creature (a floor would swamp the export)
const PROP_RE = /floor|ground|plane|backdrop|stage|base_|pedestal|light|camera|helper/;

// ── OBJ writer: one `o` block per part, positions + normals, keeps parts separable ──
function writeOBJ(meshes, name) {
  const L = ['# upperdeckripmaster3030 — morphed iteration "' + name + '"',
             '# generated by scripts/morph-mesh.mjs · RoninMorph (deterministic: seed = identity)'];
  let vBase = 1, nBase = 1;
  for (const m of meshes) {
    L.push('o ' + m.name);
    const v = m.verts, n = v.length / 6;
    for (let i = 0; i < v.length; i += 6) L.push('v ' + v[i].toFixed(6) + ' ' + v[i+1].toFixed(6) + ' ' + v[i+2].toFixed(6));
    for (let i = 0; i < v.length; i += 6) L.push('vn ' + v[i+3].toFixed(5) + ' ' + v[i+4].toFixed(5) + ' ' + v[i+5].toFixed(5));
    for (let t = 0; t < n; t += 3) {
      const a = vBase + t, b = vBase + t + 1, c = vBase + t + 2;
      const na = nBase + t, nb = nBase + t + 1, nc = nBase + t + 2;
      L.push(`f ${a}//${na} ${b}//${nb} ${c}//${nc}`);
    }
    vBase += n; nBase += n;
  }
  return L.join('\n') + '\n';
}

// ── run ───────────────────────────────────────────────────────────────────────
const parsedAll = RoninOBJ.parse(readFileSync(inPath, 'utf8'));
const dropped = keepProps ? [] : parsedAll.meshes.filter(m => PROP_RE.test(m.name)).map(m => m.name);
const parsed = { meshes: keepProps ? parsedAll.meshes : parsedAll.meshes.filter(m => !PROP_RE.test(m.name)) };
if (dropped.length) console.log('dropped props:', dropped.join(', '));
const srcName = basename(inPath).replace(/\.obj$/i, '');
mkdirSync(outDir, { recursive: true });
console.log(`source: ${srcName} — ${parsed.meshes.length} parts, ${parsed.meshes.reduce((s, m) => s + m.count / 3, 0) | 0} tris`);

for (const seed of seeds) {
  const spec = opList ? { seed, ops: opList.map(op => ({ op, amt })) } : RoninMorph.fromSlug(seed, amt);
  const out = parsed.meshes.map(m => ({ name: m.name, verts: RoninMorph.apply(m.verts, spec) }));
  const file = join(outDir, `${srcName}__${seed}.obj`);
  writeFileSync(file, writeOBJ(out, seed));
  const b = RoninMorph.bounds(out.reduce((acc, m) => { const c = new Float32Array(acc.length + m.verts.length); c.set(acc); c.set(m.verts, acc.length); return c; }, new Float32Array(0)));
  console.log(`  ${seed.padEnd(16)} ops=${spec.ops.map(o => o.op + '@' + o.amt.toFixed(2)).join('+').padEnd(34)} → ${basename(file)}  size ${b.size.map(x => x.toFixed(2)).join('/')}`);
}
console.log('done. seeds are reproducible — same seed always regenerates the same creature.');
